### ISSUE TITLE
Feature: Specifier resolution customization

### ISSUE THREAD

**Issue by GeoffreyBooth** [nodejs/modules#110]
ESM supports intra-package absolute specifiers (`/top-level-dir/module.js`) relative to a package root to avoid long unreadable `../../../top-level-dir/module.js` chains. This is currently possible in CommonJS.

ESM supports alternative resolution when running tests in order to achieve convention-driven mocking: `import './x'` prefers `./x.test.js` if it exists, rather than the usual `./x.js`. This is currently possible in CommonJS.

`@`-prefixed bare-specifiers that refer to dependencies via an out-of-band manifest file (that defines the mapping similar to `package-name-maps`) can be loaded by Node without a build step.

If I forget to list all my dependencies in `package.json`, I could run my Node app in a strict asserting mode where name resolution will fail if my code accidentally imports:
- bare-specifiers not explicitly listed as dependencies (this can be achieved today for the top level project by installing dependencies with the npm option `--global-style` at the cost of having one layer of nesting of installed modules)
- relative-specifiers that wander into dependencies, i.e. `node_modules`

I can write a small sample module on a web-based JavaScript editor like [JS Bin](http://jsbin.com/?html,js,output) that can import modules from NPM (e.g. the unpkg use case).

I can deploy an app into production, but serve common modules like RxJs from a CDN.

I can depend on a dev build during development and a prod build in production.

Use case 23, 24, 26, 27, 29, 30, 31, 33. See also #109 for compatibility with browsers.

**Comment by benjamingr** [comment]
> ESM supports intra-package absolute specifiers (/top-level-dir/module.js) relative to a package root to avoid long unreadable ../../../top-level-dir/module.js chains

It does as ESM? How?

**Comment by GeoffreyBooth** [comment]
> It does as ESM?

The feature request is that it does somehow.

**Comment by ljharb** [comment]
Right, but how does CJS support that?

**Comment by devsnek** [comment]
by hacking `Module._resolveFilename`, which i would not consider a model to follow. right now node's esm has resolve hooks which can handle this use case.

**Comment by jdalton** [comment]
See [module-alias](https://www.npmjs.com/package/module-alias) for an example.

**Comment by bmeck** [comment]
@GeoffreyBooth To clarify would this mean that `/` no longer refers to the root of the fs when using `import`?

**Comment by GeoffreyBooth** [comment]
I’m not sure that Meteor accomplish this via transpilation, I just know that it _is_ transpiling. It might very well be using one of those hacks. I think it’s a reasonable request that ESM be similarly hackable.
