### ISSUE TITLE
Feature: Conditional imports

### ISSUE THREAD

**Issue by GeoffreyBooth** [nodejs/modules#113]
Node should provide an ESM equivalent of:

```js
if (process.env.DEBUG)
  var { inspect } = require('util');
```

In other words, let users tell Node to potentially not load modules or module exports into memory, if they might not be used.

Use case 41.

**Comment by benjamingr** [comment]
Note that from reading about it it doesn't look like top-level await which is what we discussed last time is going to happen. 

Then again, this can be done with dynamic import syntax. The problem is dynamic imports are contagious.

**Comment by MylesBorins** [comment]
What gave you the impression that top level await is not going to happen?
Spec text is being worked on and it is being brought to tc39 again this week

**Comment by devsnek** [comment]
there are also some other plans for conditional imports which don't rely on top-level await and some other interesting things like import fallbacks and stuff. afaik no one has made any official proposals yet but its definitely being discussed.

**Comment by benjamingr** [comment]
@MylesBorins 

> What gave you the impression that top level await is not going to happen?

Well, I was the under the impression it means [late bindings](https://gist.github.com/Rich-Harris/0b6f317657f5167663b493c722647221) for modules which I thought were a no-go.

Would love to learn more about the current status. 

> Spec text is being worked on and it is being brought to tc39 again this week

That's awesome 🎉

**Comment by ljharb** [comment]
The relevant thing tho is that if it becomes possible in the language, it will automatically be possible in nade - and if it doesn’t, it will be impossible. I’m not sure this issue is directly actionable in node (beyond pursuing changes in TC39)

**Comment by benjamingr** [comment]
> The relevant thing tho is that if it becomes possible in the language, it will automatically be possible in nade - and if it doesn’t, it will be impossible. I’m not sure this issue is directly actionable in node (beyond pursuing changes in TC39)

If it becomes possible in the language - then by definition JS will have late bindings which resolves both the CommonJS named exports issue and the "conditional imports" issue.

That's a huge fundamental impact for modules IMO. 

Moreover, this gives the commitee a chance to find a solution that's a middle-way, for example the proposal's "no exports from modules with top-level await" or "no exports after an `await` in modules with top-level await" which would solve one issue but not the other.

**Comment by ljharb** [comment]
I don’t see how top-level `await` enables late bindings such that named imports from CJS could work; could you elaborate?

**Comment by ljharb** [comment]
I’m pretty sure the 5 is only exported then; but the name “bar” would be exported immediately with a value of `undefined`, just like a hoisted variable.

**Comment by benjamingr** [comment]
> I’m pretty sure the 5 is only exported then; but the name “bar” would be exported immediately with a value of undefined, just like a hoisted variable.

Ah, so just to clarify - all the exports from top-level-awaited code would be exported immediately regardless but their values would only be updated at a later point?

**Comment by devsnek** [comment]
@benjamingr es modules already do that. they populate exports during instantiation and then evaluation actually defines the values of those exports. (except for functions, those are available right after instantiate) but anywau the only difference with top level await is that evaluation might take a bit longer.

@ljharb iirc trying to access `bar` before it gets its value should throw a reference error.

**Comment by ljharb** [comment]
@devsnek sure, I’ll buy the tdz error :-) but that’s still an early static binding, like everything else.

**Comment by benjamingr** [comment]
> @benjamingr es modules already do that. they populate exports during instantiation and then evaluation actually defines the values of those exports. 

Right, but without top-level await is there a way to tell the difference between the two?

Thanks a lot for explaining by the way @ljharb @devsnek, this makes a lot more sense now that I understand it's hoisting rather than late bindings.

**Comment by ljharb** [comment]
```js
export let foo;
setTimeout(() => { foo = 3; });
```
altho that wouldn’t give a tdz, i believe.

**Comment by devsnek** [comment]
@ljharb i get tdz testing that

```js
> const x = new vm.Module('export let foo; setTimeout(() => { foo = 3; });');
undefined
> void x.link(() => 0)
undefined
> x.instantiate()
undefined
> x.namespace
[Module] { foo: <uninitialized> }
> x.namespace.foo
ReferenceError: foo is not defined
```

**Comment by guybedford** [comment]
@devsnek did you mean to execute in your example above? TDZ only appears
when dealing with circular references in ES modules, and definitely comes
up in those cases as you can access a binding before it is evaluated.

Simplest example would be x.mjs:

import * as self from ./x.mjs’;
console.log(x.p);
export let p = 5;

Via node —experimental-modules x.mjs

**Comment by guybedford** [comment]
Sorry I mean ‘self.p’ in the above not ‘x.p’

**Comment by devsnek** [comment]
@guybedford ah sorry I thought we were taking about pre-evaluate. nice example.

**Comment by ljharb** [comment]
No JS can run pre-evaluate, that’s the whole point/problem :-p

**Comment by guybedford** [comment]
That is by definition I think :)
