### ISSUE TITLE
Worker implementation

### ISSUE THREAD

**Issue by guybedford** [nodejs/modules#118]
For those who haven't seen it yet, the modules group may have some interest in this one - https://github.com/nodejs/node/pull/20876.

Part of the modules specification in HTML is "worker modules" (yet to land in browsers) through `new Worker('module.js', { type: 'module' })`, so may be worth considering if this would also be supported in Node and some of the overall workflows here.

Note also on the web, `new Worker(import.meta.url)` works fine, but in NodeJS fileURLs are not currently supported for the worker constructor creating some extra boilerplate needs on the universal workflow here.

**Comment by benjamingr** [comment]
I think it's a little too early to discuss this (from the worker side).

**Comment by addaleax** [comment]
I’m happy to adjust the PR with suggestions from the WG, though. :)

**Comment by guybedford** [comment]
@addaleax thanks for keeping an eye here and for your great work on this.

@benjamingr certainly not aiming to move towards any decisions here, but in terms of longer-term big picture it can be a useful exercise to consider.

I must admit a part of me wishes we could have unified on `import.meta.Worker` for a module worker in a module scope to allow easy universal workflows like:

```js
new import.meta.Worker('./relpath.js');
```

being a module worker by default with the above working in both Node and browsers.

**Comment by benjamingr** [comment]
I think it would be interesting to discuss this in the module meeting during the collaborator summit - if anyone is interested.

**Comment by guybedford** [comment]
One of the trickiest parts of the differences between `new Worker` between web and Node is that `new Worker` takes a file path in Node and a URL on the web, meaning a lot of boilerplate will be needed when writing universal worker-based code.

My hope is that we can come up with an approach to reduce this boiler plate to enable very simple universal workflows. This was actually my major intention for creating https://github.com/nodejs/node/pull/20950.

**Comment by benjamingr** [comment]
@guybedford I think consensus on the worker proposal so far is that in the future `Worker` will be able to accept a (local) URL as a parameter as well as a relative path (and perhaps even a function).

**Comment by guybedford** [comment]
@benjamingr I don't see anything along these lines discussed in the worker PR, do you have a reference here at all?

**Comment by guybedford** [comment]
Ideally I'd hope `new Worker` could accept a direct file URL itself to match the web.

**Comment by MylesBorins** [comment]
As workers has landed I'm going to close this. please re-open if this was premature
