### ISSUE TITLE
Node.js Foundation Modules Team Meeting 2018-06-20

### ISSUE THREAD

**Issue by jdalton** [nodejs/modules#126]
## Time

**UTC Wed 20-Jun-2018 19:00 (07:00 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Wed 20-Jun-2018 12:00 (12:00 PM) |
| US / Mountain | Wed 20-Jun-2018 13:00 (01:00 PM) |
| US / Central  | Wed 20-Jun-2018 14:00 (02:00 PM) |
| US / Eastern  | Wed 20-Jun-2018 15:00 (03:00 PM) |
| London        | Wed 20-Jun-2018 20:00 (08:00 PM) |
| Amsterdam     | Wed 20-Jun-2018 21:00 (09:00 PM) |
| Moscow        | Wed 20-Jun-2018 22:00 (10:00 PM) |
| Chennai       | Thu 21-Jun-2018 00:30 (12:30 AM) |
| Hangzhou      | Thu 21-Jun-2018 03:00 (03:00 AM) |
| Tokyo         | Thu 21-Jun-2018 04:00 (04:00 AM) |
| Sydney        | Thu 21-Jun-2018 05:00 (05:00 AM) |

Or in your local time:
* http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Modules%20Team+Meeting+2018-20-06&iso=20180606T19
* or http://www.wolframalpha.com/input/?i=07PM+UTC,+Jun+20,+2018+in+local+time

## Agenda

This meeting is to discuss transparent interop with the goal of informing and coming to a decision on if-any-transparent interop should be possible _(by default, or by loader, or by otherwise)_. Please keep in mind transparent interop is a large umbrella. We should clarify and make clear distinctions about what we are discussing _(one sided, two sided, etc.)_.

Other Items:

* governance: s/pull request/issue for new members (#128)
* Pull request opened for import.meta.require on core (#130)
* Have presentation on loaders. (#135)
* Add features list to README (#134)

## Invited

* Modules team: @nodejs/modules

**Comment by GeoffreyBooth** [comment]
Can we carve out 3 minutes to hopefully approve #128 and #134? Basically to see if we have unanimous consent to merge them in. If anyone has any objections, we can leave the PR open and punt the discussion into the next meeting.

**Comment by ljharb** [comment]
I believe that we don't need unanimous consent; we need quorum (50%) of the 28 voting members.
 - #128 has 12 approvals already, so it only needs two more before it can be summarily merged (not counting the OP, 50% of 27 rounds up to the same 14 approvals).
 - #134 has 5 approvals, so it needs 9 more.

**Comment by benjamingr** [comment]
An old friend reached out to me about meeting today and it might cause me to miss the meeting - if you have anything to vote on other than the two issues let me know (and I hope we do @bmeck's presentation on loaders so I can catch up on that with the video )

**Comment by bmeck** [comment]
@benjamingr I think that slide deck is not easily fit into the current meeting where we are still discussing transparent interop and what it means (ESM importing CJS, CJS requiring ESM, or bi-directional). That topic will be a rather large one on our agenda and the deck I have takes a good 30minutes to run through.

**Comment by ljharb** [comment]
Could we get a meeting link?

**Comment by mhdawson** [comment]
I think the same one should be good from last last time.  Looking for it.

**Comment by mhdawson** [comment]
https://zoom.us/j/656987750

**Comment by demurgos** [comment]
Youtube link: https://www.youtube.com/watch?v=RIdJMD42ZGs

**Comment by robpalme** [comment]
On Zoom I just see "Please wait for the host to start this webinar" yet on YouTube the meeting is happening.

**Comment by MylesBorins** [comment]
@robpalme the meeting just ended :(
