### ISSUE TITLE
Feature: Spec compliance

### ISSUE THREAD

**Issue by GeoffreyBooth** [nodejs/modules#132]
The modules implementation that ships as part of Node core is fully compliant with all relevant specifications.

Use case 59.

(For many people this kind of goes without saying, but I think it’s worth enumerating as a feature to be prioritized along with all the other features and goals of the implementation.)

**Comment by bmeck** [comment]
I'd note that this is a meta-feature, it affects basically everything and isn't exactly a feature in itself?

**Comment by GeoffreyBooth** [comment]
Yeah, feature, meta-feature, however you want to describe it. I think it _is_ worth mentioning, as I feel like there shouldn’t be “assumed” features or requirements that we’re not specifying.

It’s also probably not a bad idea to give this a thread of its own, as there’s definitely some debate as to the spec itself on certain points, such as whether it covers CommonJS or not, etc. @bmeck do you have some links to the relevant spec or specs? Those would be good to include in the top post.

**Comment by devsnek** [comment]
> I feel like there shouldn’t be “assumed” features or requirements that we’re not specifying.

as long as we're still making es modules we are inherently following a specification. if the final product doesn't match the spec it isn't es modules, its something else.

**Comment by bmeck** [comment]
@GeoffreyBooth 
I could just state the general phrasing that I'm starting to lean on:

> Spec text is not implementation text, see [conformance criteria](https://tc39.github.io/ecma262/#sec-conformance) , an [example of expected optimization in contradiction with spec text implementation](https://tc39.github.io/ecma262/#sec-map.prototype.delete) , and [algorithm conventions](https://tc39.github.io/ecma262/#sec-algorithm-conventions).

from: https://docs.google.com/presentation/d/14Jn4ry0rlONMd2Yc1ZdFl-aU42XKVEgOc9x2Hy9C9ZI/edit?usp=sharing

All things integrating with the spec need to abide by the same conformance and algorithm criteria, regardless of if it is documented in the specification or not that includes loading CommonJS/JSON/HTML due to the algorithm conventions callout about semantics.

**Comment by ljharb** [comment]
It's node dot JS, i think it's definitely assumed that it complies with the JS spec.
