### ISSUE TITLE
Should we skip next weeks meeting?

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/modules#143]
It is happening on the 4th of July... A national holiday for many members

**Comment by jdalton** [comment]
Oh snao! I'll be out.

**Comment by jkrems** [comment]
I'll be out as well.

**Comment by ljharb** [comment]
It’d be nicer to reschedule it - we have a lot to talk about. Any chance that’s viable?

**Comment by weswigham** [comment]
> Oh snao! I'll be out.

Same. If we could move it to another day that week it'd be good, or I suppose the following week would be reasonable for most (not myself though, I'm leaving the country on vacation on the 9th for a week and a half).

**Comment by MylesBorins** [comment]
Anyone can propose a time or make a doodle 😄

**Comment by GeoffreyBooth** [comment]
Personally I'd love to just move to July 11 (the following Wednesday) and then stick to every other Wednesday after that.

But unless that magically works for everyone, yeah, let's do a doodle.

**Comment by MylesBorins** [comment]
@GeoffreyBooth I'm up for moving one meeting but I think it is a bad idea to permanently shift the meeting without doing a doodle of the entire group. I for example have a conflict on alternating weeks. It is easy for me to move 1 meeting but more complicated for recurring meetings.

I'm assuming that this may be the case for various folks

**Comment by ljharb** [comment]
July 25th is TC39, as well.

**Comment by GeoffreyBooth** [comment]
Are we meeting on July 4?

**Comment by mhdawson** [comment]
I don't think Myles will be available either, as he has the same conflict as I do.

**Comment by ljharb** [comment]
Even though only 11 people have responded (12 including Myles), it seems like we should have the next meeting on July 11th at the usual time (with the following meeting on July 18th - ie, the usual schedule).

**Comment by demurgos** [comment]
@SMotaal 
The usual time is UTC 19:00 (07:00 PM), convert it to your own time zone.

**Comment by ljharb** [comment]
#148 has the new meeting info (altho the date is currently wrong, should be the 11th not the 10th)
