### ISSUE TITLE
Managing Signal to Noise

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/modules#15]
Discussions about the module implementation can be quite contentious and lead to very long threads that mix both implementation and philosophy. Personally I have found the amount of content churning out to be quite overwhelming in the past, and already see this beginning to happen in this repo.

How can we focus the conversation so as to not drive away potential collaborators and minimize the investment of time necessary to get started.

One suggestion to kick this off. Moving general discussion about concepts to a chat room and keep the issue tracker focused on implementation discussion? The line on this could be quite blurry, which is a concern

To be explicit, I in no way want to discourage people from having an open discourse, I just want to figure out the balance that can keep people engaged and avoid the pattern of "whoever talks the longest wins"

**Comment by bmeck** [comment]
We should use something that isn't IRC that actually keeps a history.

**Comment by benjamn** [comment]
https://gitter.im works great for real-time chats connected to GitHub repositories, in my experience.

**Comment by yjoyos** [comment]
I think right here it make sense to use zulip, It threaded discussion will help keeping the noise level low making sure you get the whole history of things :). Even more you can limit signups to invite only.

zulipchat.com

**Comment by yjoyos** [comment]
+ You can have bot that posts the commit anytime it pushed to nodejs/modules repo.

> https://gitter.im works great for real-time chats connected to GitHub repositories, in my experience.

Are you sure? I don;t think single thread that is going to have lots of discussion be feasible for having better conversations @benjamn.

**Comment by benjamn** [comment]
@yjoyos Thanks for the idea, but I'm not sure I have time to debate with folks who are not members of this working group. You just signed up for GitHub, and have no history whatsoever.

@MylesBorins Should we lock this repo down to the invited members? Signal vs. noise, and all…

**Comment by yjoyos** [comment]
I though process was not to have a debate with anyone 😞. Sorry for troubling you guys.

 > You just signed up for GitHub, and have no history whatsoever.
Btw, i am a former gitlab user. Never knew you you guys are not welcoming.

**Comment by benjamn** [comment]
No need to be sorry. We're trying to get a specific kind of work done, and this issue is all about the risks of losing focus. I'm glad to know that Zulip exists.

**Comment by MylesBorins** [comment]
@fishrock123 had suggested using discourse to the org. Perhaps this would
be a good place to pilot it considering how many stakeholders we have

**Comment by weswigham** [comment]
discourse isn't really a chat service, is it? More of a forum, very similar in functionality to github issues. If we're just looking to separate actual issues or tasks with discussion, we could use [github team discussions](https://github.com/orgs/nodejs/teams/modules), since they're already integrated here.

**Comment by devsnek** [comment]
we really need a more instant sort of chat to prevent against the enormous books of text we all tend to write on more forum based solutions like github

**Comment by TimothyGu** [comment]
I think @mylesborins might have meant Discord?

Discord or Slack for me. Slack has a slight advantage in its threads support. I’ve used Gitter a long time ago and wasn’t a great fan but am willing to try it again.

**Comment by TimothyGu** [comment]
Or IRC, which has been very effective in my discussions with @devsnek and @bmeck.

**Comment by MylesBorins** [comment]
I did indeed mean Discord 🤦‍♂️ 

@Fishrock123 was mentioning the ability to do video chat on discord, and potentially being able to do the youtube streaming video from it, or perhaps trying another service like twitch. As this group is much larger than the average working group it may be worth exploring a new stack for doing live streamed meetings

/cc @Amorelandra has some advice on this

**Comment by devsnek** [comment]
@MylesBorins video chat in discord is group dm only and limited to 10 people

**Comment by MylesBorins** [comment]
Gtk, not a good candidate then

**Comment by targos** [comment]
I would very much like to try Discord! I don't think video chat is a must have.

**Comment by ljharb** [comment]
I strongly dislike Discord's UI; I'd prefer IRC and to have a logging bot in the channel for those without a bouncer.

**Comment by evanplaice** [comment]
It may be useful if we could establish a format for consensus issues

Title: Consensus: [issue]
Body

- the body starts with the `Status: blocking | confirmed`
- the body contains details/specifics about the issue
- the body includes a `References` section that points to other issues related to the consensus

Comments

- each member posts one comment on the issue
- the comment starts with `Consensus: agree | disagree | abstain`
- the body contains details/concerns

If this sounds beneficial, I can quickly make up a PR with a template.

**Comment by MylesBorins** [comment]
@evanplaice I think it is a good idea, but I'm not entirely sure we need that level of process.

One thing to keep in mind about node's consensus model is that while we require explicit sign off on the implementation we don't require people to explicitly agree, rather we give people an opportunity to dissent. I'd imagine that most times where we are trying to reach explicit consensus on something moving forward would happen in a PR.

**Comment by MylesBorins** [comment]
I feel like we had a good discussion about this today. Closing for now. Feel free to reopen or start a new conversation on this topic.
