### ISSUE TITLE
Feature: Ability to run resolver from within a module

### ISSUE THREAD

**Issue by guybedford** [nodejs/modules#157]
There is no feature currently tracking this, so I'm creating this and immediately closing so that we can have a reference for the features document.

The use case here is being able to resolve a module specifier from within a module context.

Current usage in Node.js is `require.resolve('asdf')`.

**Comment by ljharb** [comment]
I’d love to see `import.meta.resolve` - and it’s the sort of thing the browser may even be willing to provide, or even the language itself.
