### ISSUE TITLE
Adding last minute participants

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/modules#16]
I've had three individuals reach out independently about having missed the deadline as they did not see the call for participants.

Are there any objections to allowing a couple late comers before we have a chance to solidify membership policies?

**Comment by TimothyGu** [comment]
No objection from me.

**Comment by benjamingr** [comment]
No objections from me, although the team is getting quite large (>25) which will be interesting to manage. We should probably see how many actually show up for meetings and participate and go from there..

**Comment by WebReflection** [comment]
let me know when these have accepted the invitation so I'll update the related page (unless somebody else would like to do that)

> the team is getting quite large (>25)

I agree but I also think some key player is missing in this team, I hope I'll find one in the next 3 candidates.

**Comment by MylesBorins** [comment]
If there are no objections by end of day tomorrow I'll add the people who have reached out. I'm not going to openly advertise this... but if you see this message and would like to be included, consider this a last chance to reach out.

**Comment by MylesBorins** [comment]
I've added the last batch of individuals, closing
