### ISSUE TITLE
Managing fork and agreed upon minimal kernel

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/modules#166]
Making this issue to track discussion and gain consensus around what a minimal kernel would look like in that fork.

**Comment by MylesBorins** [comment]
what would we want to call the fork? node-esm?

**Comment by devsnek** [comment]
how about a branch called `esm`

**Comment by MylesBorins** [comment]
So this is a good thing to discuss

Fork vs branch.

With branches on node core we have one less thing to worry about (a new
repo) but are creating lots of noise for other collaborators (feature?)

A new repo allows us a sandbox, but creates a separate place for
conversations to go (aside from the modules repo)

We could mount node as a Subtree in the modules repo and do pull requests.
This is a bit of a spaceship though.

**Comment by GeoffreyBooth** [comment]
The other thing to discuss is what should go in Node core. Do we keep the current implementation there? Replace it with a minimal one that grows over time? Remove it and leave nothing, and various implementations are all relative to an ESM-less core?

**Comment by giltayar** [comment]
+1 for fork. Until we know where this is going, the less noise, the better.

**Comment by giltayar** [comment]
What should go in? Leave everything as is, as this is the easiest, and
start discussing what should be taken out. (or put in.)

**Comment by devsnek** [comment]
> It will not look for index.js because that will provoke a "file extension debate", and we all want to evade that.

node looks for index.{any registered file extension} atm, will we still support that?

**Comment by GeoffreyBooth** [comment]
I think folder lookup can be something else that gets added later. If you _really_ want to be minimal, you could also leave out package resolution, to allow for either the CommonJS `require` algorithm or the package name maps proposal.

**Comment by MylesBorins** [comment]
Minimal kernel imho:

* No transparent interop
* import only supports ESM
  - no json
  - no common
  - no native modules
  - perhaps explicit ban on .js extension for now
* No extension searching (move https://github.com/nodejs/node/pull/21729 to the fork and iterate)
* createRequireFunction to allow for cjs in esm interop (move https://github.com/nodejs/node/pull/19360 to the fork and iterate)
* dynamic import to allow for esm in cjs interop

**Comment by devsnek** [comment]
i would still say that any situation where we land without node resolution enabled by default is unworkable, and so it should be part of the kernel.

**Comment by MylesBorins** [comment]
@devsnek I don't agree with you, and thus we don't have consensus. We can't remove it later and thus I think it shouldn't be in the kernel

**Comment by giltayar** [comment]
@MylesBorins - I'm assuming your minimal kernel also doesn't assume an extension, and the extension has to be explicitly in the name?

**Comment by MylesBorins** [comment]
@giltayar indeed

**Comment by targos** [comment]
@MylesBorins thanks for creating the repo. Should we start by pushing node's master branch to it?

**Comment by MylesBorins** [comment]
I'm trying to push right now. Super slow wifi 😅

**Comment by MylesBorins** [comment]
Fork is up and running

--> https://github.com/nodejs/ecmascript-modules

**Comment by michael-ciniawsky** [comment]
`pkg.module` ?  Or will `pkg.main` still lookup the file extension (as an exception)? This feels inconsistent/confusing if paths searching is removed... 

> ⚠️ Note I'm not talking about support `.js` for ESM or the like, just how this is supposed to work 


**`package.json`**
```js
{
  "main": "./file" // What happens if e.g ./file.js || ./file.mjs is explicitly defined?
}
```

**`package.json`**
```js
{
  "main": "./file.js",
  "module": "./file.mjs"
}
```

?

**Comment by MylesBorins** [comment]
@michael-ciniawsky I think the intent was to support `package.main` as a means to specify the entry point of a module, and that this path would need to be explicit (no path searching).

We were debating if this should even be supported, perhaps it should be dropped.

**Comment by MylesBorins** [comment]
here's a doc so people can comment and offer suggestions for changes. If you would like to suggest alternative proposals please do so in the issue

https://docs.google.com/document/d/1uq3v1h3dUXmjMAabQCsxdj7Ig2lOpaty1u4HcUi8whQ/edit?usp=sharing

**Comment by michael-ciniawsky** [comment]
So no 'dual-mode' packages (for now) ?

**Comment by MylesBorins** [comment]
indeed. It is something that would be part of a future enhancement to the kernel, dependent on the feature set

**Comment by MylesBorins** [comment]
We have a PR open to solve this, going to close the issue
