### ISSUE TITLE
Today's meeting

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/modules#171]
Hey all,

I'm on vacation this week... Someone else will have to pick up getting the meeting going

@mhdawson are you able to kick off the zoom?

@jdalton do you want to chair?

Anyone wat to use "make-node-meeting" to generate the agenda?

**Comment by mhdawson** [comment]
I'm double booked at that time, but I can start the zoom and then I'll have to hand off to @jdalton and drop off

**Comment by jdalton** [comment]
I am unable to chair today _(a bit under the weather)_.

**Comment by guybedford** [comment]
I could chair the meeting again if it would help.
