### ISSUE TITLE
Node.js Foundation Modules Team Meeting 2018-08-29

### ISSUE THREAD

**Issue by guybedford** [nodejs/modules#172]
## Time

**UTC Wed 29-Aug-2018 19:00 (07:00 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Wed 29-Aug-2018 12:00 (12:00 PM) |
| US / Mountain | Wed 29-Aug-2018 13:00 (01:00 PM) |
| US / Central  | Wed 29-Aug-2018 14:00 (02:00 PM) |
| US / Eastern  | Wed 29-Aug-2018 15:00 (03:00 PM) |
| London        | Wed 29-Aug-2018 20:00 (08:00 PM) |
| Amsterdam     | Wed 29-Aug-2018 21:00 (09:00 PM) |
| Moscow        | Wed 29-Aug-2018 22:00 (10:00 PM) |
| Chennai       | Thu 30-Aug-2018 00:30 (12:30 AM) |
| Hangzhou      | Thu 30-Aug-2018 03:00 (03:00 AM) |
| Tokyo         | Thu 30-Aug-2018 04:00 (04:00 AM) |
| Sydney        | Thu 30-Aug-2018 05:00 (05:00 AM) |

Or in your local time:
* http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Modules%20Team+Meeting+2018-08-29&iso=20180815T19
* or http://www.wolframalpha.com/input/?i=07PM+UTC%2C+Aug+29%2C+2018+in+local+time

## Links

* **Minutes Google Doc**: <https://docs.google.com/document/d/1DhUZYo8Cw-CNZCnnsV8qVPA0WeK6SH2kt971Rt0DqR0/edit?usp=sharing>
* **Previous Minutes Google Doc**: <https://docs.google.com/document/d/11SQ4Ib5jdyusHPJfGG_aJR2lsTAX1oAiiGklL2EHxhw/edit?usp=sharing>

## Agenda

Extracted from **modules-agenda** labelled issues and pull requests from the **nodejs org** prior to the meeting.

### approving PRs (1 minute timebox)

* Nominate @SMotaal as an active member [#162](https://github.com/nodejs/modules/issues/162)

### Update on Progress (4 minute timebox)

* Create Terminology.md [#158](https://github.com/nodejs/modules/pull/158)
  - 2 minute timebox
* Developer Survey [#85](https://github.com/nodejs/modules/issues/85)
  - 2 minute timebox

### ECMAScript Modules PRs (25 minute timebox)

Extracted from PRs against https://github.com/nodejs/ecmascript-modules prior to the meeting.

* import.meta.require [#1](https://github.com/nodejs/ecmascript-modules/pull/1)
* remove file extension and directory resolving [#2](https://github.com/nodejs/ecmascript-modules/pull/2)
* remove ".json" default loading [#3](https://github.com/nodejs/ecmascript-modules/pull/3)
* default extensions and directory resolving across package boundaries [#4](https://github.com/nodejs/ecmascript-modules/pull/4)

### Discussion (30 minute timebox)

* Browser / bundler compatibility [#170](https://github.com/nodejs/modules/issues/170)
* Managing fork and agreed upon minimal kernel [#166](https://github.com/nodejs/modules/issues/166)
* Proposals for configuring parse goals of files in --experimental-modules [#160](https://github.com/nodejs/modules/pull/160)

## Invited

* Modules team: @nodejs/modules

## Notes

The agenda comes from issues labelled with `modules-agenda` across **all of the repositories in the nodejs org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Joining the meeting

* link for participants: https://zoom.us/j/656987750
* For those who just want to watch: https://www.youtube.com/c/nodejs+foundation/live

**Comment by guybedford** [comment]
Please anyone feel free to edit the agenda or make suggestions if I have missed anything as well.

**Comment by GeoffreyBooth** [comment]
Can we also discuss #160? I know it’s about creating a PR against the current implementation rather than the new one, but I feel like the work that goes into it will very likely find its way into the new implementation as well.

**Comment by guybedford** [comment]
@GeoffreyBooth sure I've added it on as another discussion item. I was under the impression it was discussed last week, or did time run out?

**Comment by SMotaal** [comment]
Sorry for the last moment... I just added modules agenda item #173

**Comment by SMotaal** [comment]
It seems not everyone in attendance listed themselves in the minutes... Does anyone have a list so we can mention them here to get it done?

**Comment by SMotaal** [comment]
- @LJHarb (Jordan Harband)
- @zenparsing (Kevin Smith)
- @fishrock123 (Jeremiah 

--- Here are the ones already in the list:

* Wesley Wigham
* Daniel Rosenwasser
* Geoffrey Booth
* Bradley Farias
* Guy Bedford
* Gus Caplan
* Saleh Abdel Motaal
* John-David Dalton

--- 

Did I miss anyone?

**Comment by guybedford** [comment]
That seems right to me, thanks.

**Comment by rubys** [comment]
I was present. Will check the minutes when i get back home
