### ISSUE TITLE
Surveys: Initial Drafts

### ISSUE THREAD

**Issue by SMotaal** [nodejs/modules#173]
This initiative is intended to yield Google Form based survey to be able to prioritize group decisions. The goal is to build a survey that feels right to developers across the Node's ecosystem, which requires more effort than just being able to write some good questions from one's own perspective.

Please note that the efforts related to this thread are now concluded. Please look forward to updates on next steps.

---

- [x]  🎉 Incremental Surveys (Ax) — #175

---

**Next Steps** open to anyone interested in collaborating on this

We're shifting gears to a more manageable facilitated questionnaires with 3-4 participants at a time in Vancouver. The "public" developers survey will now only be feasible after the summit.

Here is an open link to the most recent "ongoing" draft: [C1: ~~Developers~~ Collaborators Survey](https://goo.gl/wcSZNR)

- ✋ Internal Surveys (Bx)

- 🔨Collaborator's Facilitated Questionnaires (Cx)
   > Version 1 — due Oct2
   > Version 2 — due Oct5

- 🔨Developers Surveys (Dx)

<pre>

    🎉done    🔨ongoing    ✋pending
</pre>

**Comment by zenparsing** [comment]
This looks good - I'll be happy to be involved in the iteration process.

**Comment by bmeck** [comment]
I'd like to be involved, but am confused as to what that looks like. I'm more looking to review the survey questions, not to take the survey.

**Comment by SMotaal** [comment]
I know... my bad, it's kinda how my head feels most of the time

**Comment by devsnek** [comment]
I'm very interested in this, please count me in.

**Comment by MylesBorins** [comment]
I believe @seldo would be interested in helping to promote the survey via
npm.

I'm sure the foundation could help with this as well.

I believe survey monkey is what they had used.

**Comment by GeoffreyBooth** [comment]
Me too.

**Comment by inidaname** [comment]
Scheduling for 2-3 days will be Friday or Saturday so which do you choose @SMotaal

**Comment by seldo** [comment]
I would anti-recommend surveymonkey; they have absurdly naive anti-XSS protection that prevents including the word "JavaScript" in a survey question; this is still not fixed.

**Comment by sendilkumarn** [comment]
Lets find a suitable timing, created a [doodle](https://doodle.com/poll/wz3q6brww9idfuaa)

**Comment by mcollina** [comment]
How will the be the form circulated? Is the "event" mentioned, Node+JS Interactive? or the collaborator Summit?

**Comment by SMotaal** [comment]
@mcollina I would assume and would like it to be both "events", but this really is up to the group as a whole. We're just trying to pick up momentum to make it possible.

**Comment by SMotaal** [comment]
I guess the A1 post-survey review can be Friday with myself, @inidaname and @sendilkumarn (please check doodle Aug 31 7PM GMT)

Any preferences between Skype or Hangouts? I know sometimes the region sort of determines that for us, so please let me know which works best.

**Comment by sendilkumarn** [comment]
I think Hangouts is fine 👍

**Comment by SMotaal** [comment]
@GeoffreyBooth Sorry about that... I will up this thread with next steps and figure out a how to make sure our efforts stay coordinated as we proceed.

**Comment by SMotaal** [comment]
Re #175 Survey: Initial Draft Incremental Rounds

Everyone taking part the incremental rounds of the (pubic) survey, as things start to move forward we will try to coordinate our efforts through #175 using direct mentions only.

Given the ad-hoc nature of this organically evolving process and how it is different from how normally collaborate, the direct mentions rule should help us stay up to day with our individual next steps.

@nodejs/modules-members

**Comment by SMotaal** [comment]
I hope we can discuss this issue to:

1. Explain the outputs gained from everyone's participation
2. Allow participants to share their own views and expectations
3. Discuss next steps
4. Closing this issue?
