### ISSUE TITLE
@rubys requesting membership

### ISSUE THREAD

**Issue by Trott** [nodejs/modules#176]
A membership request for @rubys was submitted through the usual GitHub interface mechanism, but the GOVERNANCE doc in this repo says it needs to be made here and added to the modules meeting agenda. So here's an issue. kthxbai

**Comment by Trott** [comment]
(I guess this is a request for initial observer status as membership would be a second request after that typically.)

**Comment by mhdawson** [comment]
+1

**Comment by MylesBorins** [comment]
Welcome to the team @rubys!!!
