### ISSUE TITLE
Session at Collab Summit Vancouver

### ISSUE THREAD

**Issue by mcollina** [nodejs/modules#177]
Hi Folks,

It would be brilliant to have a session about Modules in Vancouver.

Who would like to lead that?

**Comment by MylesBorins** [comment]
I can definitely help... anyone else wanna pitch in?

**Comment by SMotaal** [comment]
With the revival of the survey, I've been considering it might be very useful to use Vancouver as a platform for unrolling the survey. If others like the idea of on-site survey efforts and having them coordinated with/around the session I am happy to volunteer to lead the survey efforts and support other efforts.

**Comment by sendilkumarn** [comment]
@SMotaal I like this idea of on-site surveys 👍

**Comment by mcollina** [comment]
We will have *massive* attendance at Collab Summit. We can for example, ask during the Code & Learn. It's a 250 people.

**Comment by sendilkumarn** [comment]
I think we can split it between days and ask people to fill them out. More input is always better

**Comment by MylesBorins** [comment]
The second day will have significantly less people than the first day. We can make going through the survey part of the code + learn and get 200+ responses

**Comment by SMotaal** [comment]
@MylesBorins I think those 200+ responses constitute a very rare kind of sample to find as far as surveys go

**Comment by SMotaal** [comment]
Is there a possibility/need for a non-member wanting to become involved to help around collab coding or other sessions?

**Comment by targos** [comment]
I think it would be awesome if we could use some time to brainstorm the new API for loaders

**Comment by devsnek** [comment]
@targos I think we should hold off on that a bit. there are still invariants we aren't 100% sure of which means big changes might need to be made anyway.

**Comment by targos** [comment]
@devsnek Then should we talk about those invariants?

**Comment by devsnek** [comment]
@bmeck will you be at the summit?

**Comment by jkrems** [comment]
I won't be able to be there in person - will there be a way to participate online?

**Comment by devsnek** [comment]
any word on this being streamed or zoomed?

**Comment by MylesBorins** [comment]
I will set up the zoom... But in not sure how well we are setup to let
external folks contribute

**Comment by MylesBorins** [comment]
https://zoom.us/j/392385291

**Comment by sendilkumarn** [comment]
@MylesBorins is webinar expired?

**Comment by MylesBorins** [comment]
It is, the session was yesterday.

Closing

**Comment by SMotaal** [comment]
For those who participated in the survey and wanted to follow-up:
Surveys: Following-up with Participant #202
