### ISSUE TITLE
Surveys: Purpose and Scope

### ISSUE THREAD

**Issue by GeoffreyBooth** [nodejs/modules#182]
Building off of https://github.com/nodejs/modules/issues/175#issuecomment-421115763, @SMotaal asked me to moderate a discussion to determine the purpose and scope of the survey(s) we intend to produce. So . . . what do you want the group to get out of these surveys? What, if anything, do you _not_ want the survey to address?

**Comment by SMotaal** [comment]
Thank you @GeoffreyBooth, imho, this is something that you and others who have a direct end user base for which they have specific indicators that they want to verify and/or justify — to help reach consensus, and in the chance that they fall short on delivering, the can show why our collective decisions made sense.

**Comment by SMotaal** [comment]
To help people start the discussion, maybe it helps to share the results view of our (not so pilot) pilot run from last meeting: https://goo.gl/VdcyXV

**Comment by SMotaal** [comment]
@GeoffreyBooth I think this is okay to close

**Comment by GeoffreyBooth** [comment]
Just so this is here, I’m assuming that there will be some internal debate as we continue to develop our new modules implementation and we’re forced to address controversial topics. When that day comes, and it already has for some of the things in the [file specifier proposal](https://github.com/GeoffreyBooth/node-import-file-specifier-resolution-proposal), I would like to use surveys to help gauge user preferences.
