### ISSUE TITLE
Surveys: Live Sessions (Oct 9-13 5:30 PM UTC)

### ISSUE THREAD

**Issue by SMotaal** [nodejs/modules#183]
📆
~~Daily Summit Surveys Planning Meetings~~ (Canceled due to lack of interest)
~~<sup>Tuesday (Oct9) thru Saturday (Oct13) at 9:30 PM (UTC)</sup>~~

Those meetings are for anyone interested in moderating surveys with groups of 3-5 people at a time at the summit.

<details>

Time: Oct 9, 2018 5:30 PM Eastern Time (US and Canada)
    Every day, until Oct 13, 2018, 5 occurrence(s)
    Oct 9, 2018 5:30 PM
    Oct 10, 2018 5:30 PM
    Oct 11, 2018 5:30 PM
    Oct 12, 2018 5:30 PM
    Oct 13, 2018 5:30 PM
    Please download and import the following iCalendar (.ics) files to your calendar system.
    Daily: https://zoom.us/meeting/637963419/ics?icsToken=c233628d1cc305a19806d7093e5a7e1b56d1cd0ef30ffc91745b75669fafe812

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/637963419

Or iPhone one-tap :
    Canada: +16475580588,,637963419# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        Canada: +1 647 558 0588 
        Australia: +61 (0) 8 7150 1149  or +61 (0) 2 8015 2088 
        Bahrain: +973 1619 8488  or +973 1619 7601 
        Dominican Republic: +1 829 956 2188  or +1 829 947 9220 
        France: +33 (0) 7 5678 4048  or +33 (0) 1 8288 0188 
        Greece: +30 231 118 0599  or +30 211 198 4488 
        Hong Kong, China: +852 5808 6088 
        Japan: +81 (0) 524 564 439  or +81 (0) 3 4578 1488 
        Mexico: +52 554 161 4288  or +52 229 910 0061 
        South Africa: +27 87 551 7702  or +27 87 550 7717 
        Switzerland: +41 (0) 31 528 0988  or +41 (0) 22 518 9006 
        United Kingdom: +44 (0) 20 3695 0088  or +44 (0) 20 3051 2874 
        US: +1 669 900 6833  or +1 646 558 8665 
    Meeting ID: 637 963 419
    International numbers available: https://zoom.us/u/adNVKrGFi5

</details>

**Comment by SMotaal** [comment]
Sorry for running a little behind... I just started (audio only) zoom: https://zoom.us/j/913116297

**Comment by SMotaal** [comment]
@sendilkumarn @tzmanics I apologize for not closing the loop on this sooner...

Since we are likely rescheduling, please indicate your availability: https://doodle.com/poll/ktn7m45cqcidtu8n

**Comment by jdalton** [comment]
The meeting is rescheduled for today (Thurs) right?

**Comment by lappang-cheung** [comment]
Observation allowed?

**Comment by SMotaal** [comment]
Everyone is welcome to join… I'll be adding the link on top roughly 5-10 mins ahead of the meeting

**Comment by SMotaal** [comment]
Here is today's link:  https://zoom.us/j/531544871

**Comment by SMotaal** [comment]
📆
Last Meeting
<sup>Thursday September 19 8-9 PM (UTC)</sup>
> 
> Thanks everyone for joining… I will try to post some updates for those who missed before our next regular meeting time.
> 
> **FYI** We received a complimentary *unlimited* time extension to that one meeting moments before the 40 minutes limit was up (thanks to the folks at Zoom)
> 
> ---
> 
> Based on [Survey Discussion](https://doodle.com/poll/ktn7m45cqcidtu8n) doodle:
>   - @tzmanics 
>   - @jdalton 
>   - @sendilkumarn 
>   - @smotaal — Will post zoom link 10 minutes before
> 
> ---
> 
> **What is the best way to move forward?**
> 
> A bunch of us are passionate about input from the community, and some are also really motivated to find ways to accept differences of opinion as means for reaching consensus. Those perfect surveys will not happen without the efforts of every single member of the group.
> 
> **Should we use this week's usual meeting time to discuss the survey?**
> **Note**: This is has nothing to do with the biweekly meetings*
> 
> Please bare in mind that I am not doing this because I am leading, but simply because I want a few of us to find what they are best able to take charge off so we can lead a collaborative effort together.

**Comment by MylesBorins** [comment]
Did this happen? Can this be closed?

**Comment by MylesBorins** [comment]
Closing
