### ISSUE TITLE
Surveys: (no/go?) I will be adding a project board for surveys today

### ISSUE THREAD

**Issue by SMotaal** [nodejs/modules#194]
We’d like to set up a project board for surveys in nodejs/modules.

Because we need it today, I will wait until a reasonable enough time Pacific before I actually create it to make sure you have no problems with that.

cc @MylesBorins @sendilkumarn

**Comment by MylesBorins** [comment]
Go for it

**Comment by targos** [comment]
Go go go!

**Comment by SMotaal** [comment]
Created [Surveys](https://github.com/nodejs/modules/projects/5) project!

**Comment by sendilkumarn** [comment]
Yay 👍
