### ISSUE TITLE
Modules Session - Collaborator Summit - Thursday Oct12 9:15 AM (Pacific)

### ISSUE THREAD

**Issue by SMotaal** [nodejs/modules#199]
The Module's session which will be held in the main hall is scheduled for Thursday Oct12 9:15AM thru 10:45AM (Pacific Time) per the [Collaborator Summit agenda](https://github.com/nodejs/summit/blob/master/2018-10-Vancouver/agenda.md)

Since those sessions offer opportunity for others who may be in attendance and are interested to contribute to or learn about our group's efforts, anyone able to join in through Zoom is encouraged to do so. 

**FYI**: Please check this thread a few minutes before the start of the session for the link which maybe be different than the one for the usual slot.

**Comment by MylesBorins** [comment]
Here is a link to the zoom

https://zoom.us/j/392385291

We will do our best to have people talk into the mic and to get dialed in folks on the PA system.

**Comment by SMotaal** [comment]
https://docs.google.com/forms/d/1cVFVb1DXfRASx0kJSuG_C_JmcaDFzLp1EskNVNHFE6k/edit

**Comment by SMotaal** [comment]
Wow, sorry about that everyone... I completely got the day of the week wrong 😄

**Comment by SMotaal** [comment]
FYI: For those who participated in the survey and wanted to follow-up:
  Surveys: Following-up with Participant #202
