### ISSUE TITLE
Should we have a steering committee

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/modules#20]
The current governance model of the project would cause any issue that this group cannot reach consensus around to be sent to the TSC. As we have such a large group with varying opinions, I think it is highly likely that we will have to deal with resolving disagreements and situations where we can't reach consensus.

So I'd like to propose that we spin up a steering committee to help guide this group and act as a stop gap prior to TSC escalation.

There is somewhat of a prior art for this with the release team, where we have the top level release working group and a number of teams spun up underneath (LTS, Releasers).

Thoughts?

**Comment by benjamingr** [comment]
I say we see who we're left with after 2 meetings and a month first and solve it then if it's a problem

**Comment by weswigham** [comment]
@benjamingr We could formalize this by saying that continued membership requires attending N meetings per period of length M.

**Comment by bmeck** [comment]
I'm slightly opposed, but would not stop it. We don't even have a specific set of consensus requirements for this group currently I believe.

**Comment by MylesBorins** [comment]
I'm going to close this for now. We can revisit later if it seems neccessar
