### ISSUE TITLE
Minimal core in userland

### ISSUE THREAD

**Issue by jkrems** [nodejs/modules#201]
Since getting custom node builds deployed to our infrastructure is pretty painful, I went ahead and implemented the minimal core (as far as it's spelled out) as a library: https://github.com/jkrems/loader.

High level observations:

1. It was easier than I expected to make it work against a vanilla node 10.12 build.
2. I ended up with a synchronous `resolve` stage and an asynchronous `fetch` stage. This turned out to make the `LoadModuleJob` a lot easier to follow and verify.
3. The `ModuleWrap` gained the ability to create both modules from source (via `.compile`) and from values (via `.setLazyStaticExports`).
4. I threw in `WASM` support mostly to validate the mime-based loading pipeline. It shouldn't actually be enabled by default.

My goal was to create a loader that can be used to quickly try out how different resolution / fetching / init combinations could work against some of our internal codebases but maybe this could actually also make it easier to iterate on the minimal core in general.

**Comment by jkrems** [comment]
If there's interest in going down this path, I'd be happy to bring the project under the control of the working group.

**Comment by devsnek** [comment]
@jkrems this looks pretty cool.

I also developed my own implementation of this sort a few months ago, which is how I arrived on issues related to debugging, tracing, resource ownership, etc that I mentioned whenever we last talked about this. Aside from that, it wouldn't be tenable to try to keep a userland package updated while we're still developing all this, as there is still a lot of movement in both node core and v8.

Experimenting is great and obviously encouraged but I don't think it would be a good use of our groups's time to pursue this as a method of official development. Additionally, the whole point of this group is to ship ecmascript modules in node core, so I think we should remain under that constraint.

**Comment by SMotaal** [comment]
I will not share my view on if this should be the path to take until everyone has had a chance to give this a thorough consideration. Regardless, I honestly think it is important to capture your efforts, and I don't mean to have you write up something for the benefit of those who are not willing to make an effort.

Who is willing to collaborate with me on creating a technical document on this (@jkrems I assume you are in support of this)?

**Comment by sendilkumarn** [comment]
@jkrems this is pretty cool 👍 

> on creating a technical document on this

The findings and the lessons learnt on this experiment will obviously help us in shaping the `esm` in the node core.

**Comment by devsnek** [comment]
@SMotaal I'm not saying people shouldn't work on these projects, I'm saying I don't want to spend group time working on issues that come up from things not being in core. We need to ship an actual implementation in core, and so the time we as a group spend on development should focus on that implementation, with all its limitations and annoyances.

**Comment by jkrems** [comment]
> I also developed my own implementation of this sort a few months ago

Yeah, this sort of work has a long, time-honored tradition. IIRC the class name `ModuleWrap` and the core module job logic originates in an [earlier hack I did ~2 years ago](https://github.com/jkrems/import/blob/sketchy/src/module_wrap.cc). This definitely doesn't replace an implementation in core longer term. :)

> issues related to debugging, tracing, resource ownership

I think it would be really valuable to document these. Because it will help us to make sure they are in fact addressed in the core implementation.

> Additionally, the whole point of this group is to ship ecmascript modules in node core, so I think we should remain under that constraint.

Absolutely. The ultimate goal has to be to have official support for ES modules in node core. But whatever lands there will have to stand the test of time ("perfect on arrival") and if there's no validation before that, it will be very hard to have any confidence that it will be usable/useful. Even shipping a minimal core with loader hooks is a strong commitment to a pretty specific direction.

> Aside from that, it wouldn't be tenable to try to keep a userland package updated while we're still developing all this, as there is still a lot of movement in both node core and v8.

My personal take is that it would be harder to keep a whole node fork up-to-date than something that uses only the public API surface area. It depends on what we're optimizing for - if we want to wait for dynamic module support in V8 before shipping a first usable implementation, then yes. Building it in node core would be our only real option.

Just to clarify the intent here: I wanted to play around with the core assumptions of the loader implementation in node core. E.g. when `ModuleWrap` is created, how linking works, what phases exist. At least for me it was a whole lot faster and easier to push that kind of higher level experimentation into files on disk instead of trying to recompile for each change.

**Comment by jkrems** [comment]
> We need to ship an actual implementation in core, and so the time we as a group spend on development should focus on that implementation, with all its limitations and annoyances.

In terms of the group's time: The thing I'd like to discuss in the context of the group is mainly the `README.md` of that repo which contains a draft for a more refined API and some suggested semantics. The actual implementation in the repo is secondary.

**Comment by SMotaal** [comment]
@devsnek I fully appreciate the tremendous efforts which mostly end up landing in your direction, and trying to consider a different perspective on how to best unleash the potential that others can bring to ultimately support your efforts. This is why I held off on voting go/no and instead wanted to create an opportunity that will have others look close enough and immerse directly in the details of implementation.

**Comment by jkrems** [comment]
This has been discussed and IIRC we decided that as a WG we don't want to support a userland implementation.
