### ISSUE TITLE
@bmacnaughton requesting membership/observer

### ISSUE THREAD

**Issue by bmacnaughton** [nodejs/modules#211]
I develop Solarwinds APM agent for node and am directly impacted by changes to module loading.

Packages like `stealthy-require` and `esm` present problems. My primary interest is in making sure there is a viable way to patch required modules in order to instrument them.

**Comment by GeoffreyBooth** [comment]
+1. Out of curiosity, what problems do those modules present?

**Comment by bmacnaughton** [comment]
`stealthy-require` unloads already loaded modules. Our instrumentation module sends an init message on load as well as modifying the `require` module so newly loaded modules (that we instrument) get patched for instrumentation. `stealthy-require`'s unloading the cache results in two init messages and the patching referring to an instance of our module that is no longer loaded.

`esm`, if loaded first, breaks us. With node 10.11.0, `esm`, in combination with us, causes a core dump. The command line:

`node -r appoptics-apm -r esm index.js` where `index.js` is an empty file results in a core dump.

I haven't dug deeply into it because the customer is fine with running node 8 but I'll have to at some point.

**Comment by bmacnaughton** [comment]
@devsnek - I know it's not yours and I wish it didn't exist. I'll ask them for support at some point when I have time to isolate the issue or when the customer can't use node 8.

**Comment by MylesBorins** [comment]
Approved with quorum in the meeting
