### ISSUE TITLE
Remove loader from upstream

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/modules#220]
Since we have consensus that we are not going to ship either of these implementations should we consider removing them upstream to halt adoption?

**Comment by devsnek** [comment]
we have concensus not to ship vm.SourceTextModule? i certainly don't agree with that.

**Comment by guybedford** [comment]
I think we should remove these only when we have an adequate replacement. Allowing users to experiment and engage with modules is important through both of these APIs, and taking them away sends a bad message too.

**Comment by MylesBorins** [comment]
@devsnek removed the VM module from this discussion and we can focus on the loader implementation

**Comment by guybedford** [comment]
@MylesBorins my point applied to both. I'm strongly against removing loader from master until we have a replacement.

**Comment by MylesBorins** [comment]
@guybedford cool. closing this for now 👍🏽
