### ISSUE TITLE
How does someone become an observer?

### ISSUE THREAD

**Issue by bnb** [nodejs/modules#224]
Currently in the [Team Membership](https://github.com/nodejs/modules/blob/master/GOVERNANCE.md#team-membership) section of the GOVERNANCE.md file, it is stated:

> New Members to the team are initially accepted as Observers.

That said, there's no statement around how to become a New Member in this file nor could I find that anywhere else in the repo.

@aerze is an individual who expressed an interest in helping out with this work in a discussion with @zkat and myself. I'd like to help get them involved if at all possible 🤗

**Comment by aerze** [comment]
Hiya, yeah I was wondering how exactly I can get involved and help out :)

**Comment by devsnek** [comment]
you can just open an issue to request to be an observer and then we'll approve it at the next meeting.

**Comment by MylesBorins** [comment]
Closing as the question has been answered
