### ISSUE TITLE
Resolution proposal

### ISSUE THREAD

**Issue by guybedford** [nodejs/modules#228]
Creating an issue for the proposal in https://github.com/GeoffreyBooth/node-import-file-specifier-resolution-proposal. Which has come out of various discussions between members of the group spearheaded by @GeoffreyBooth.

Ideally this should get at least 15 - 20 mins on the agenda, as working through the resolver intricacies is critical to our current phase 2 plans.

**Comment by MylesBorins** [comment]
Updated agenda for 20 minutes to discuss

**Comment by MylesBorins** [comment]
@domenic it would be interesting to get your 2c on this

**Comment by domenic** [comment]
I guess I find it confusing how the proposal adds a lot of CommonJS interop stuff at the same time as working on ES import resolution stuff. Or maybe it's not an addition, and there's already CommonJS interop? I haven't been keeping track of what exists so far and what doesn't.

That said, if I try to detangle that and only focus on the "import Statements of ESM Packages and Files" subsection, that seems nice and minimal and browser-compatible.

**Comment by guybedford** [comment]
Let's continue to discuss any specific aspects of this proposal in the repo there at - https://github.com/GeoffreyBooth/node-import-file-specifier-resolution-proposal.
