### ISSUE TITLE
Discussion: Organizing work

### ISSUE THREAD

**Issue by GeoffreyBooth** [nodejs/modules#230]
Building off of @SMotaal and @bmeck’s interrupted discussion at the end of last meeting, I think it might be useful to discuss maybe semi-formalize our process for how smaller groups are working? I’ve found the small-group model to be very productive so far for Phase 2-3 and Phase 2-4, so I’d like to encourage it and find ways for it to work for everyone.

https://github.com/nodejs/modules/pull/196#issuecomment-432817177 is a group-editable comment where people were invited to say which parts of Phase 2 they wanted to be involved in; that could perhaps be better managed somewhere else, maybe a wiki page on this repo? Or even as PRs to the Phase 2 roadmap doc, perhaps with pre-approved permission for members to add or remove their names without needing quorum. Such a list defines who is on each small group for the parts of Phase 2 (or beyond).

For the Phases 2-3 and 2-4 groups, we’ve had a long-running Google Hangouts chat with all involved members and we’ve used that to set up calls and so on, ideally finding times that work for everyone. (This is where the smaller the group the better.) I don’t know if there’s a better option (Slack?) or something else that people would prefer, but I think it’s important to try to keep as much communication involving the entire small team whenever possible. This complements the small teams themselves being open to anyone interested in participating in that topic.

Anyway these are just suggestions, I guess we can treat this as a discussion thread if people want to suggest other ways for organizing the work that’s happening on the new implementation. I’m just so excited that we’re making progress that I want to help all the groups keep moving forward 😄

**Comment by SMotaal** [comment]
@GeoffreyBooth being made to feel invisible (intentional or not) is something no one wants to deal with by choice, so I find myself discouraged to see that when I am clearly being excluded and seemingly on a subconscious level to feel that the rest of the group is either not appreciating my burden or not appreciating that it is a burden. I have no words to explain how sad this leaves me.

**Comment by GeoffreyBooth** [comment]
Yes, well, that’s why I’m suggesting structures to ensure that that doesn’t happen. We’re all members of this group and we should all be entitled to work on any part of the new implementation, and that includes participating in planning discussions. It’s important to plan in an open way, open to anyone who wants to be a part of that work effort.

**Comment by SMotaal** [comment]
I shared and even pushed for this sentiment until today's meeting. But there is clearly a threshold for every person, and it has now passed, and with respect, admiration and gratitude to you and the majority of the members, to have to reconcile all the great progress I am honoured to take small part in with the isolated but unchecked marginalization by a single peer puts me in deadlock. If a member is unable to see their peers as equal members, they have no place in the group, and if they do, then the group needs to address the repercussions of such behaviours when they are thrown onto one of their peers. I will not drop out, I will not give in and accept it, but that is not the same thing as saying that things are fine, let's move on.

**Comment by MylesBorins** [comment]
I'd like to suggest that we move any discussion about personal
relationships off this thread and I'd kindly ask that people moderate
comments related to specific relationship issues.

If people feel that individuals are not acting within the guidelines of our
oeganizations code of conduct they are free to make a report to
@nodejs/moderation

There is a hard balance between asking people to be transparent and telling
people where / when / who they can work with.

Our teams governance mentions nothing about everyone needing to be included
in all conversations nor that people working on team related issues having
to do so within the confines of the group. None of us are entitled to other
people's time, but we should work towards collaborating as much as possible.

If we want to make stronger membership expectations we should do so in a
separate issue.

Unless this issue has a very directed outcome I think we should close this.

**Comment by GeoffreyBooth** [comment]
I guess it’s up to the small groups themselves how they want to conduct their work, but I think at least having a place where it’s listed who’s working on what (or interested in what) would be helpful. We can do better than that comment I posted in that thread a few weeks ago. Would a wiki page be an option?

**Comment by SMotaal** [comment]
@GeoffreyBooth So can we say this issue is not actionable and if there is work to be done to address the high level concerns then we can explore those in separate issues if needed (thanks for taking the initiative though)?

**Comment by GeoffreyBooth** [comment]
Well at least we can have a document—a wiki page, a Google doc, something—where we can scratch out who’s working on what. Something editable to help keep the team organized.

**Comment by SMotaal** [comment]
So do we want to propose the idea of a project board in the meeting?

But how would we structure that?

**Comment by MylesBorins** [comment]
Closing this as there has been no movement in a while, please feel free to re-open or ask me to do so if you are unable to.
