### ISSUE TITLE
Type Error: Method Map… incompatible receiver (with --expose-internals)

### ISSUE THREAD

**Issue by SMotaal** [nodejs/modules#238]
This issue has been nagging at me for a few months and until now it seemed to be only scoped to <samp>--experimental-vm-modules</samp> but that is no longer true.

**Versions**: 11.4.0 and [irp-implementation](https://github.com/guybedford/node/tree/irp-implementation)

**How to reproduce**

1. Create a folder with a simple `esm.mjs` (and `esm.js` for irp-implementation):

   > ```js
   > export default 'esm is awesome';
   > ```

   *Note*: for irp-implementation you may need a `package.json` with ESM features in the current folder or the first parent folder with a `package.json`:

   > ```json
   > {
   >     "exports": {}
   > }

2. Run node as follows with your respective esm entry:
   
   ```sc
   $ node --experimental-vm-modules --expose-internals --experimental-modules esm.mjs
   ```
   
   make sure to drop <samp>--experimental-vm-modules</samp> and <samp>--experimental-modules</samp> for irp-implementation as follows:
   
   ```sc
   $ node --expose-internals esm.js
   ```

3. Expected output will include:
   
   ```red
   TypeError: Method Map.prototype.has called on incompatible receiver [object Object]
       at Proxy.has (<anonymous>)
       at Loader.getModuleJob (internal/modules/esm/loader.js:132:24)
       at process._tickCallback (internal/process/next_tick.js:43:7)
       at executeUserCode (internal/bootstrap/node.js:317:13)
       at startExecution (internal/bootstrap/node.js:242:3)
       at startup (internal/bootstrap/node.js:193:3)
       at internal/bootstrap/node.js:692:1
   error Command failed with exit code 1.
   ```

**Comment by devsnek** [comment]
@SMotaal can you open this on https://github.com/nodejs/ecmascript-modules

**Comment by devsnek** [comment]
fwiw this error came from a file in `lib/internal/vm` that was doing `module.exports = new Map()` that doesn't exist anymore.

**Comment by SMotaal** [comment]
Moved to [ecmascript-modules#21](/nodejs/ecmascript-modules/issues/21)
