### ISSUE TITLE
January 2nd Meeting availability

### ISSUE THREAD

**Issue by weswigham** [nodejs/modules#241]
Having another meeting to come to consensus on some more stuff before the next TC39 meeting on January 29-31st is important for us, but the 2nd is immediately following a major holiday. To ensure we actually have sufficient attendance, we should check who's available on the 2nd and reschedule to the 9th is need be.

Edit: Up-thumb react if you can make the meeting on the 2nd, down-thumb react if you can't.

**Comment by MylesBorins** [comment]
TC39 is 29 - 31... but I think we need lead time to get work done prior to the meeting.

I'm not available on the 2nd but could do the 3rd or 4th if we don't want to delay a week.

It may also be reasonable to think about having an extra meeting in January either way

**Comment by ljharb** [comment]
TC39 is on the 29th.

I’m available on the 2nd.

**Comment by jdalton** [comment]
I'm traveling back on the 3rd.

**Comment by weswigham** [comment]
Ah, quick poll so people don't need to comment if they don't feel like it: Up-thumb react on the OP if you can make the meeting on the 2nd, down-thumb react on the OP if you can't. We can take a tally next week and decide if the meeting needs to be rescheduled.

**Comment by weswigham** [comment]
(For reference, it looks like attendance tomorrow will be OK)

**Comment by ljharb** [comment]
Do we have a meeting issue and a zoom link?

**Comment by weswigham** [comment]
I don't think we do, no

**Comment by weswigham** [comment]
Well, zoom link is the same as last meeting, at least, I'd assume so.

**Comment by weswigham** [comment]
Although without myles available I'm not sure who can start it~

**Comment by SMotaal** [comment]
I can set us up with my own zoom account (but no streaming)

**Comment by SMotaal** [comment]
Should I do that?

**Comment by bmeck** [comment]
Sounds good to me.

**Comment by SMotaal** [comment]
Okay here is a link: https://zoom.us/j/524778216?pwd=U3hsaFhqNkw1K3pjMjZGYlYwd3Brdz09
(FYI pwd modules)

**Comment by bmeck** [comment]
we can use https://docs.google.com/document/d/1wNfy77yvQvBf7YP1x01izLEDGIjn9BbVqpaPvJXsj7E/edit for temp minutes

**Comment by SMotaal** [comment]
thanks 👍

**Comment by MylesBorins** [comment]
Hey all, 

did yesterday's meeting get recorded / streamed?
