### ISSUE TITLE
Structuring a "Breakout Teams" project board

### ISSUE THREAD

**Issue by SMotaal** [nodejs/modules#244]
Let's discuss how we want to structure the [Breakout Teams](/nodejs/modules/projects/6) project board here which was created per last meeting discussions related to [Discussion: Organizing work #230](https://github.com/nodejs/modules/issues/230).
---

**Proposed Structure**

- [ ] Board

   - [ ] Purpose: **to coordinate breakout teams efforts across phases**

   - [x] [Template: **None**](https://help.github.com/articles/creating-a-project-board/)
           We're simply using this to structure efforts

- [ ] Columns

   - [ ] General: Structure (top), announcements, overlapping issue cards... etc.

   - [ ] Teams: Spotlight (top), events, milestone checklists, specific issue cards... etc.

   - [ ] Meta: References, community matters... etc.

---
Updated regularly to reflect decisions reach below.

**Comment by SMotaal** [comment]
Please join #244 for discussing how we want to structure the newly created teams board ([/nodejs/modules/projects/6](/nodejs/modules/projects/6)). I'd like to invite members from the various teams to coordinate and to begin creating and populating respective columns to help us figure what works best more organically.
 
cc @nodejs/modules

**Comment by MylesBorins** [comment]
Closing this as there has been no movement in a while, please feel free to re-open or ask me to do so if you are unable to.
