### ISSUE TITLE
Detecting syntax errors from node internals

### ISSUE THREAD

**Issue by zenparsing** [nodejs/modules#254]
This is a purely technical node internals question...

I'm currently experimenting with a design where I've made the following changes to node/v8:

- Modified the v8 parser to detect when an import or export statement is encountered while parsing a statement list in a script and throw a syntax error with a specific error message.
- Modified the CJS loader in node to detect those syntax errors.

Currently, I'm detecting these specific errors on the node side by matching against the error's `message` property. The error message detection looks something like this:

```js
function esmSyntaxError(err) {
  return err instanceof SyntaxError && (
    err.message === 'Cannot use \'import.meta\' outside a module' ||
    err.message === 'Import declaration cannot appear outside a module' ||
    err.message === 'Export declaration cannot appear outside a module'
  );
}
```

It's working for the prototype, but it's clearly less than ideal. Do any of the node experts here have a better idea for how I might detect these syntax errors coming from the JS engine? Are there any other instances in node where engine error "types" are detected?

Thanks!

**Comment by zenparsing** [comment]
Thanks, I thought that might be the case.

> (btw detecting by name/message is not good since node is also run in with other engines like chakra and graal)

Yeah, I know : )

> Can you give some more detail on what you're working on?

Over the weekend I put together a prototype non-transparent-interop solution which has the following features:

- ESM can be loaded with ".js" as a main file (by doing the syntax error detection trick)
- ESM can be loaded in `-r` preload scripts (ditto)
- `import.meta.require`/`dirname`/`filename`
- package.json "module" key support
- folder imports via index

Here's the [diff](https://github.com/nodejs/node/compare/master...zenparsing:esm-yay) for the curious.

**Comment by robpalme** [comment]
Agreed. With good error messages, we quickly have a good-enough UX for a consumer who doesn't initially know if their importee supports ES named exports.

At worst, they bump into the error and respond by switching to the default import. At best, the IDE intell-sense figures this out for them and it works first time.

**Comment by ljharb** [comment]
This kind of seems like errors that would be better off being added to each engine - trying to use `import`/`export` in a Script, or `with` in a Module, etc, should be able to provide a helpful error message in any engine.
