### ISSUE TITLE
Roadmap doc

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/modules#261]
For next Wednesday we are going to want to sketch out a roadmap, identify contentious areas that we need to reach consensus on or vote.

Started sketching ideas in this doc... please make suggested edits or comment

~~https://docs.google.com/document/d/1O3DvnrNfIUVnW6rSqzjWq3aI--XdKy74uTCRiFw1vTI/edit?usp=sharing~~

edit:

https://docs.google.com/document/d/1DSWrdV1fzXvlOdTZ5MngDX7v6CU4ZUheJ7ysOZ2uK0w/edit?usp=sharing

**Comment by devsnek** [comment]
@MylesBorins i'm getting access denied on that

**Comment by MylesBorins** [comment]
Can you try again? Access should be open

**Comment by MylesBorins** [comment]
Looks like there may be acl issues because the doc was made from my internal Google account.

I'll transfer to personal account and update links when I'm back at keyboard. In the mean time please request access and I'll do my best to share in a timely fashion

**Comment by MylesBorins** [comment]
New link: https://docs.google.com/document/d/1DSWrdV1fzXvlOdTZ5MngDX7v6CU4ZUheJ7ysOZ2uK0w/edit?usp=sharing


I'll update original comment

**Comment by MylesBorins** [comment]
Feel like this has run it's course
