### ISSUE TITLE
Stage 2-6: Initial entry points proposal

### ISSUE THREAD

**Issue by GeoffreyBooth** [nodejs/modules#262]
For the Stage 2-6 case involving initial entry points (`node file`, `--eval`, `STDIN`, etc.), I’ve prepared a proposal that builds off of our current implementation: 
https://github.com/GeoffreyBooth/node-esm-entry-points-proposal

Feedback welcome **as issues in that repo please.** Also please note that all names of things are subject to change as the process goes on, and especially in Stage 4 when we get user feedback. All names should be considered placeholders.

**Comment by MylesBorins** [comment]
Can this be closed?

**Comment by GeoffreyBooth** [comment]
Yes.
