### ISSUE TITLE
Out of band meeting: Wed Feb 20 3pm ET

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/modules#267]
Are people available during our regular slot?

Wed Feb 20 3pm ET

👍🏽 yes
👎🏽 no

Write in with preferred time

**Comment by robpalme** [comment]
Would it be possible to delay it by 1 hour?

**Comment by MylesBorins** [comment]
@robpalme unfortunately one hour later conflicts with the Node.js TSC meeting (as well as another conflicting meeting I have 😇)

**Comment by evanplaice** [comment]
Will this be streamed. If not, can I just join in as a silent observer?

**Comment by MylesBorins** [comment]
@evanplaice you are an observer in the team, you are welcome to join all calls!

**Comment by GeoffreyBooth** [comment]
What’s the agenda for this? Continuing to discuss the items in the [Google doc](https://docs.google.com/document/d/1DSWrdV1fzXvlOdTZ5MngDX7v6CU4ZUheJ7ysOZ2uK0w/edit#) from last time?

Are we planning to just finish our discussion of `import` of CommonJS, or is the plan to also continue beyond that?

**Comment by MylesBorins** [comment]
@GeoffreyBooth I was assuming we would pick up where we left off last week. Finishing discussion related to interop, digging into file extensions, and then requirements.

**Comment by ljharb** [comment]
→ #270
