### ISSUE TITLE
Loading binaries in ES Modules

### ISSUE THREAD

**Issue by guybedford** [nodejs/modules#279]
Given that we removed support for `.node` files in ECMAScript modules, the assumption is that we would use `process.dlopen` to load binaries.

`process.dlopen` will create a new binary instance each time it is used or throw an error. Will this still be sufficient for binary loading?

**Comment by guybedford** [comment]
//cc @jasnell

**Comment by devsnek** [comment]
we can just pass .node through to the cjs loader. simple change.

**Comment by guybedford** [comment]
@devsnek that means that any module that imports a `.node` file is now no longer browser-compatibile unless it does so in a conditional with dynamic import.

**Comment by devsnek** [comment]
huh

**Comment by ljharb** [comment]
Any module using process.binding wouldn’t be either, though?

**Comment by addaleax** [comment]
I’m confused – is this about `process.dlopen()` (official API for loading native addons manually) or `process.binding()` (deprecated, evil access to Node’s internals)?

**Comment by addaleax** [comment]
Also note that `process.dlopen()` doesn’t have nice effects of `require()` like ensuring that the returned value is a singleton for each file. When calling it twice on an addon, it will either fail or give you a new instance of the module.

**Comment by guybedford** [comment]
Ah, I mixed this up with `process.dlopen` yes :) Thanks @addaleax for correcting me here.

**Comment by addaleax** [comment]
@guybedford I do feel like ESM should have a better way than raw `process.dlopen()` for loading addons.

**Comment by guybedford** [comment]
> Also note that `process.dlopen()` doesn’t have nice effects of `require()` like ensuring that the returned value is a singleton for each file. When calling it twice on an addon, it will either fail or give you a new instance of the module.

Interesting - could it be made into a singleton do you think?

**Comment by guybedford** [comment]
@addaleax sure, will reopen for discussion.

**Comment by devsnek** [comment]
they should absolutely be a supported thing to import. they have their own file extension that isn't contentious. all we need to do is pass the request to cjs, like with json

**Comment by guybedford** [comment]
@addaleax I'm not sure `process.dlopen` is so bad, since most projects bundle their binaries and are the only consumers of it.

**Comment by addaleax** [comment]
> > Also note that `process.dlopen()` doesn’t have nice effects of `require()` like ensuring that the returned value is a singleton for each file. When calling it twice on an addon, it will either fail or give you a new instance of the module.
> 
> Interesting - could it be made into a singleton do you think?

It would be a breaking change, and I think it depends on whether we ever want to allow loading addons from different contexts/realms.

I don’t think `process.dlopen()` is *terrible*, but yeah, it’s also not the most convenient thing to use.

**Comment by guybedford** [comment]
In addition if you look at usage on `npm`, most libraries don't do `require('./x.node')` and rather have a custom wrapper using `require('bindings')('./x.node')` or similar. These projects all effectively would want the `process.dlopen`-style usage.

**Comment by MylesBorins** [comment]
I think it is worth considering that wasm modules will hopefully replace the 90% case of native modules. AFAIK many packages that expose native modules expose a CJS interface that in turn brings in the native module itself. I'm going to dig into some of the top native modules and see what interface they expose and post findings in here

**Comment by weswigham** [comment]
I'm less sure about that - a lot of native module exist to provide bindings for a dynamically linked system lib - even if you can take those libs and compile them to wasm, you'd lose the platform behaviors and dynamic linking (if they even still work without binding to platform APIs). Although it's probably preferable for things like decoders and encoders and other things that were just rewritten as a native module for perf. Upsides and downsides, I suppose.

**Comment by MylesBorins** [comment]
Can this be closed?

**Comment by guybedford** [comment]
Feel free to close, my original questions were answered on this.
