### ISSUE TITLE
Out of band meeting to discuss file extension and directory resolution 2019-03-04

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/modules#282]
## Time

**UTC Mon 04-Mar-2019 21:00 (09:00 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Mon 04-Mar-2019 13:00 (01:00 PM) |
| US / Mountain | Mon 04-Mar-2019 14:00 (02:00 PM) |
| US / Central  | Mon 04-Mar-2019 15:00 (03:00 PM) |
| US / Eastern  | Mon 04-Mar-2019 16:00 (04:00 PM) |
| London        | Mon 04-Mar-2019 21:00 (09:00 PM) |
| Amsterdam     | Mon 04-Mar-2019 22:00 (10:00 PM) |
| Moscow        | Mon 04-Mar-2019 00:00 (12:00 AM) |
| Chennai       | Tue 04-Mar-2019 02:30 (02:30 AM) |
| Hangzhou      | Tue 04-Mar-2019 05:00 (05:00 AM) |
| Tokyo         | Tue 04-Mar-2019 06:00 (06:00 AM) |
| Sydney        | Tue 04-Mar-2019 08:00 (08:00 AM) |

## Links

* **Minutes Google Doc**: https://docs.google.com/document/d/1a98gcLhRPDXvdMCtzpXqqmSzCP-f232svueJAUqFJlo/edit?usp=sharing

## Joining the meeting
link for participants: https://zoom.us/j/981119692
For those who just want to watch: https://www.youtube.com/c/nodejs+foundation/live

**Comment by weswigham** [comment]
I can do 1pm ET (10am pacific), but am limited to only an hour of length due to another meeting.

**Comment by GeoffreyBooth** [comment]
I might have a conflict on Friday at 10 am PT. I'm free most of the day on Thursday and Monday. Sorry for the hassle, but do you mind doing a doodle?

**Comment by guybedford** [comment]
I won't be able to make it then, but could do 3 hours later or earlier.

**Comment by jkrems** [comment]
I said "yes" but I may have to split attention at times. Earlier or an hour later would be better.

**Comment by devsnek** [comment]
I can't do an hour later

**Comment by MylesBorins** [comment]
Doodle --> https://doodle.com/poll/3tgy2y9bg6xu2ut7

**Comment by jkrems** [comment]
I marked myself as "maybe" for Monday and Tuesday but I'm at an offsite so it would only know very short-term if I can make it work or not.

**Comment by GeoffreyBooth** [comment]
I'm assuming this isn't happening on Friday, at least not at 1 pm ET? Per the doodle it looks like the winning timeslot is Monday at 4 pm ET.

**Comment by MylesBorins** [comment]
Monday at 1 pm PT / 4 pm ET / 9 pm UTC. it is!

I've added it to the Node.js Calendar and also scheduled a zoom

https://zoom.us/j/981119692

I've called the meeting "Node.js Modules Team Extended Meeting to Resolve Resolution of Extensions", and I am pretty proud of that name. Closing out this issue, will open another issue with the agenda

**Comment by MylesBorins** [comment]
Reopening this one to track the meeting... no need for an extra issue since the agenda is a single item

## Time

**UTC Mon 04-Mar-2019 21:00 (09:00 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Mon 04-Mar-2019 13:00 (01:00 PM) |
| US / Mountain | Mon 04-Mar-2019 14:00 (02:00 PM) |
| US / Central  | Mon 04-Mar-2019 15:00 (03:00 PM) |
| US / Eastern  | Mon 04-Mar-2019 16:00 (04:00 PM) |
| London        | Mon 04-Mar-2019 21:00 (09:00 PM) |
| Amsterdam     | Mon 04-Mar-2019 22:00 (10:00 PM) |
| Moscow        | Mon 04-Mar-2019 00:00 (12:00 AM) |
| Chennai       | Tue 04-Mar-2019 02:30 (02:30 AM) |
| Hangzhou      | Tue 04-Mar-2019 05:00 (05:00 AM) |
| Tokyo         | Tue 04-Mar-2019 06:00 (06:00 AM) |
| Sydney        | Tue 04-Mar-2019 08:00 (08:00 AM) |

## Links

* **Minutes Google Doc**: https://docs.google.com/document/d/1a98gcLhRPDXvdMCtzpXqqmSzCP-f232svueJAUqFJlo/edit?usp=sharing

## Joining the meeting
link for participants: https://zoom.us/j/981119692
For those who just want to watch: https://www.youtube.com/c/nodejs+foundation/live
