### ISSUE TITLE
Meeting: Editorial for Upstream (Tomorrow/Wednesday slots)

### ISSUE THREAD

**Issue by SMotaal** [nodejs/modules#289]
- [X] Fill [doodle](https://doodle.com/poll/bp2bu5ht4d2cdki6)
- [X] Close [doodle](https://doodle.com/poll/bp2bu5ht4d2cdki6)
- [ ] Meeting `Wed Mar-6 2pm PT` (it's 1 hr but doodle gives room for more)
---

Let's meet to coordinate editorial efforts that would compliment everyone's amazing progress towards Aprils upstream implementation.

Users will surely appreciate good references to help them tap into the right setup where they can continue to use features they love or try new ones all together.

This meeting will be a good place to canvas existing and new documents that fit this bill and to get us coordinated to deliver a more coherent story across these resources.

Please start by filling this **short-term** doodle (ie options are "this" Tuesday and Wednesday)

**Comment by evanplaice** [comment]
Is there any interest in having a slide deck made available for presenting Node ECMAScript Modules?

I have one available in a repo implemented in Reveal.js. It just needs an update to reflect the current feature set and expectations for Phase III.

**Comment by GeoffreyBooth** [comment]
> Is there any interest in having a slide deck made available for presenting Node ECMAScript Modules?

Absolutely! One of the items on the [TODO list for upstreaming](https://github.com/nodejs/modules/issues/286#issuecomment-469387979) is a blog post announcing the new implementation and explaining it in article form. I think a slideshow can certainly complement that, and/or inform the writing of the article.

**Comment by GeoffreyBooth** [comment]
> Cool. I’m a bit fuzzy on the final feature set (ie there was a lot of back-and-fourth about entry points so I’m not 100% clear on what actually landed). As soon as the docs are updated to reflect the current state I’ll update the slides. Is there an official Design Guide available for Node documentation?

Nothing is final. The aim to update the docs to reflect the implementation as it stands so far. Specifically, the [ECMAScript Modules](https://nodejs.org/api/esm.html) page should describe the new implementation, not the old one.

Was there ever an official blog post about the first `--experimental-modules`? All I can find is [this one-line mention in release notes](https://nodejs.org/en/blog/release/v8.5.0/).

This third-party blog [post](http://2ality.com/2017/09/native-esm-node.html) describes the first implementation pretty succinctly. We could use it as a reference point for drafting ours.

**Comment by devsnek** [comment]
@GeoffreyBooth https://medium.com/the-node-js-collection/the-current-state-of-implementation-and-planning-for-esmodules-a4ecb2aac07a

**Comment by GeoffreyBooth** [comment]
Thanks @devsnek.

I pushed a branch with what I’ve written so far. I think we can hopefully all work in the same branch: https://github.com/nodejs/ecmascript-modules/tree/docs

https://github.com/nodejs/ecmascript-modules/blob/docs/doc/api/esm.md

There’s obviously a lot still leftover from the old implementation that needs replacing. Also I feel like the spec text at the bottom should go in a different file.

**Comment by SMotaal** [comment]
How does everyone feel about `Wed Mar-6 1pm PT`?

**Comment by ljharb** [comment]
Seems like 2pm and 3pm Wednesday have more people available?

**Comment by SMotaal** [comment]
I think the ideal thing is to lock the start at 2pm and consider a non-hard stop at 3pm — the additional hour being a discretionary opt in for those who want it.

**Comment by SMotaal** [comment]
Saleh Abdel Motaal is inviting you to a scheduled Zoom meeting.

Topic: Editorial for Upstream
Time: Mar 6, 2019 2:00 PM Pacific Time (US and Canada)

Join Zoom Meeting
https://zoom.us/j/828483241?pwd=eGhOWCtKTUI5QUJlWmlNcGtrOXhlUT09

Password: *<a href="mailto:saleh@grasppe.com">`encoded in link but email me if you need it`</a>*

One tap mobile
+16475580588,,828483241# Canada

Dial by your location
        +1 647 558 0588 Canada
        +61 8 7150 1149 Australia
        +61 2 8015 2088 Australia
        +973 1619 8488 Bahrain
        +973 1619 7601 Bahrain
        +1 829 956 2188 Dominican Republic
        +1 829 947 9220 Dominican Republic
        +33 7 5678 4048 France
        +33 1 8288 0188 France
        +30 231 118 0599 Greece
        +30 211 198 4488 Greece
        +852 5808 6088 Hong Kong, China
        +81 524 564 439 Japan
        +81 3 4578 1488 Japan
        +52 554 161 4288 Mexico
        +52 229 910 0061 Mexico
        +27 87 551 7702 South Africa
        +27 87 550 7717 South Africa
        +41 31 528 0988 Switzerland
        +41 22 518 9006 Switzerland
        +44 203 966 3809 United Kingdom
        +44 203 695 0088 United Kingdom
        +1 720 707 2699 US
        +1 646 558 8656 US (New York)
Meeting ID: 828 483 241
Find your local number: https://zoom.us/u/abhecxun3

**Comment by SMotaal** [comment]
Let me know if you have trouble joining

**Comment by ljharb** [comment]
Turns out I’ll be unable to join today.
