### ISSUE TITLE
Promote @evanplaice to member

### ISSUE THREAD

**Issue by GeoffreyBooth** [nodejs/modules#290]
@evanplaice has made lots of contributions to issues in the group and has attended many meetings, and is contributing to the docs-writing process. I think he deserves to be a group member.

**Comment by GeoffreyBooth** [comment]
(We were just on a long working call editing the docs, and he mentioned that he didn’t have write access to the repo, which made me realize that he was only an observer.)

Another very active observer is @WebReflection, if you want membership I’m happy to nominate you too.

**Comment by devsnek** [comment]
no offense to andrea but their last interaction appears to have been in october, so i wouldn't describe them as active here.

**Comment by ljharb** [comment]
@GeoffreyBooth see #66.

**Comment by GeoffreyBooth** [comment]
For some reason I was thinking it was @WebReflection who posted that big [“web modules” implementation](https://github.com/nodejs/modules/issues/278), but clearly that was @zenparsing. Maybe the “web” in both names made me misremember. My apologies to both of you.

Regardless, I still propose @evanplaice 😄. @ljharb what about #66? That looks like a thread for moving people from member to observer?

**Comment by ljharb** [comment]
@GeoffreyBooth yes, and it moved the user in question from member to observer, along with a bunch of others, for being inactive. @zenparsing is already a member. (hiding all the off topic messages; unhide if you like)

**Comment by GeoffreyBooth** [comment]
(backing up, going to clean up this thread)

(We were just on a long working call editing the docs, and he mentioned that he didn’t have write access to the repo, which made me realize that he was only an observer.)

**Comment by GeoffreyBooth** [comment]
Turns out @evanplaice already has write access as an observer, so promoting him to member isn’t necessary at the moment. Closing for now.
