### ISSUE TITLE
Google doc for blog post

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/modules#313]
Marketing is doing a quick pass for spelling errors and what not, post should go out with the 12.x release post (separate posts). Can people do one last review and confirm everything makes sense? For now it is copy pasted from the doc in this repo

https://docs.google.com/document/d/1u2PiBGTrDn9umKH3mBR_V0NAbmTXTSJ4_7wkKUgk3Ns/edit

**Comment by GeoffreyBooth** [comment]
I'll update re entry-type becoming input-type.

**Comment by jdalton** [comment]
> Marketing is doing a quick pass

Which marketing team is that?

**Comment by devsnek** [comment]
@jdalton linux foundation; they run the blogs
