### ISSUE TITLE
Migration: Characteristics of migration-friendly pseudo-esm code!

### ISSUE THREAD

**Issue by SMotaal** [nodejs/modules#314]
**If** such code existed today that worked with some `third-party-node` transpiler/bootstrapper, what characteristics of this code would actually best reflect the behavior of the same source text executing directly as ESM.

I'd like to track a list of the various characteristics which I am sure people have broadly explored or at least discussed.

**Candidates**:

1. Live bindings for `import {…}` statements
2. …

Please feel free to discuss and recommend other characteristics.

**Comment by ljharb** [comment]
I'm not sure what you're looking for, exactly - is this a list of the requirements of the ES module spec?

**Comment by GeoffreyBooth** [comment]
Maybe it would be better to list things that transpilers accept that Node ESM doesn’t (at least for now)? Like `require` in ESM mode, automatic extensions, named exports from CommonJS, etc.

**Comment by ljharb** [comment]
+1, I think it'd be a very good idea to keep a list of features we've discarded.

**Comment by SMotaal** [comment]
+1

something towards more predictable curbing of a false sense enthusiasm 😄

**Comment by bmeck** [comment]
closing due to lack of movement, feel free to reopen
