### ISSUE TITLE
Review Phase 3

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/modules#316]
Now that we have shipped 🎉we should review phase 3 in a meeting and figure out what we are going to prioritize

**Comment by GeoffreyBooth** [comment]
Current Phase 3 plan: https://github.com/nodejs/modules/blob/master/doc/plan-for-new-modules-implementation.md#phase-3-path-to-stability-removing—experimental-modules-flag

**Comment by SMotaal** [comment]
🎉

**Comment by GeoffreyBooth** [comment]
https://github.com/nodejs/modules/pull/319

**Comment by MylesBorins** [comment]
Going to keep this open to generate an ongoing agenda item for us to review phase 3
