### ISSUE TITLE
Presentation about named exports in core

### ISSUE THREAD

**Issue by mcollina** [nodejs/modules#32]
I think it would be benefit for everyone (including @nodejs/tsc) if a member of @nodejs/modules prepare a 10-20 minutes presentation on the various options for named exports (https://github.com/nodejs/node/pull/18131). I think it would help create some shared understanding behind the issue.

If we can publish that on youtube, this can also help to bring the community up to date.

**Comment by jdalton** [comment]
I can speak to my experience with a working implementation.
What is the TSC deliberating? The merits of named exports, the approach?

**Comment by mcollina** [comment]
I do not think @nodejs/tsc has deliberated anything on that regard, however I _think_ we should follow the recommendation from this group. 

I'm speaking as myself and not as @nodejs/tsc. The topic is very complex, and the ramifications are far.
Having a presentation about "this choice vs another" should allow to create some consensus.

**Comment by devsnek** [comment]
i can speak about it at the next meeting as i have a pr open to core for it but i don't know if i can come up with a youtube video

**Comment by MylesBorins** [comment]
As we landed on not wanting to focus too much on technical discussion in the recent meeting would it perhaps make sense to do this as part of the upcoming modules summit?
