### ISSUE TITLE
Loader: Allow providing source text for format: esm/json

### ISSUE THREAD

**Issue by Jamesernator** [nodejs/modules#328]
Basically as the title says, currently it seems quite painful to do something like loading over HTTP and using that text as currently the loader fetches its own resources from the URL given. It would be nice if we could instead just return the source text from the `resolve` hook (or maybe a new hook) and use that text instead.

Example:

```js
export async function resolve(specifier, parentUrl, defaultResolve) {
  if (specifier.startsWith('https://')) {
    // fetch and get sourceText
    return {
      url: specifier,
      format: // 'json' or 'esm' depending on content-type header
      sourceText: fetchedSourceText,
    }
  } else {
    return defaultResolve(specifier, parentUrl)
  }
}
```

**Comment by bmeck** [comment]
this is now a feature via [getSource](https://nodejs.org/dist/latest-v14.x/docs/api/esm.html#esm_code_getsource_code_hook)
