### ISSUE TITLE
OpenJS Summit Modules Session May 30th 2019 10am CEST

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/modules#334]
Hey All,

The modules session is coming up in 8 hours at 10am CEST (I should probably go to bed 😅)

There will be a way to dial in, still finding out the details and will post as soon as I know

There is another session on modules and security session at 14:00 CEST

**Comment by MylesBorins** [comment]
https://zoom.us/j/381668642 - Berlin/Main Room

**Comment by jkrems** [comment]
Session is starting right now! /cc @nodejs/modules-active-members
