### ISSUE TITLE
Package Exports

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/modules#341]
Proposal: https://github.com/jkrems/proposal-pkg-exports/

I know that we had punted on this as not being a modules concern, but I think that it might be something we need to land to unflag. Would like to discuss in a meeting.

**Comment by jkrems** [comment]
FYI - there's a fairly large rewrite of the proposal text going on in this doc: https://docs.google.com/document/d/1HIcO2Nyz1M_n1I18PeDgAI61XP-zzoraWyUflEjTmgc/edit#

**Comment by ljharb** [comment]
I think that to land it, it has to land for cjs first/simultaneously.

**Comment by jkrems** [comment]
Yep, the new proposal also applies to CJS. Although I can foresee concerns
about actually shipping it by default there given that it will
realistically have an impact on speed (unless we can make it fast enough
that it’s not perceptible).

**Comment by ljharb** [comment]
Whether it's on by default or off by default (on by default is better, of course), as long as it's the same for both module systems at the same time then I'm super on board!
