### ISSUE TITLE
Define package-internal mappings in exports

### ISSUE THREAD

**Issue by jkrems** [nodejs/modules#354]
Tracking issue for discussing package-internal specifier remapping. Once there's consensus on if and when we should support it, this turns into tracking the actual implementation.

**Comment by jkrems** [comment]
Important movements here by @guybedford:

1. Adding `imports` to the proposal: https://github.com/jkrems/proposal-pkg-exports/pull/40
2. Spec'ing differential mappings as part of `targets`: https://github.com/guybedford/proposal-pkg-targets

**Comment by jkrems** [comment]
Assigned to guy because he's de-facto working on this already.

**Comment by MylesBorins** [comment]
Since this landed in 13.2. I'm going to go ahead and close this. reopen if there is outstanding work
