### ISSUE TITLE
Add @jamiebuilds and @devongovett as observers

### ISSUE THREAD

**Issue by jamiebuilds** [nodejs/modules#363]
We've been working on the [Parcel](https://github.com/parcel-bundler/parcel) bundler and writing our own specifications around module resolution. We met with @guybedford today to talk about how some of our work aligns with the work of the node modules committee and work from other bundlers, and he suggested that we attend the next modules meeting.

**Comment by guybedford** [comment]
I've created a PR in https://github.com/nodejs/modules/pull/364. Even if we don't get that merged soon you can follow the instructions to join the meeting tomorrow at https://github.com/nodejs/modules/issues/362.
