### ISSUE TITLE
Add test to verify that relative imports do not trigger exports checks

### ISSUE THREAD

**Issue by jkrems** [nodejs/modules#369]
We're missing a test case for the following:

* `pkg/dir/x.mjs` imports `../hidden.js`
* `pkg/package.json` doesn't export `hidden.js`
* The import should succeed because a relative import shouldn't look at the exports map.

**Comment by guybedford** [comment]
Along these lines - it would also be worth checking the same with percent-encoding of "." (%2E) causing similar escaping.

This would likely need to be included in the package name checks and fileURLToPath implementation.

**Comment by jkrems** [comment]
This test is added as part of https://github.com/nodejs/node/pull/29327
