### ISSUE TITLE
We should have more folks with credentials to run meetings

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/modules#375]
Who wants to volunteer?

**Comment by devsnek** [comment]
I can host some meetings if needed.

**Comment by guybedford** [comment]
I'm happy to assist with hosting as well.

**Comment by MylesBorins** [comment]
@brianwarner would you be able to onboard @devsnek and @guybedford ?

**Comment by brianwarner** [comment]
Sure thing.  @devsnek and @guybedford, check your emails.
