### ISSUE TITLE
Planning: Out-of-band meetings for early September

### ISSUE THREAD

**Issue by SMotaal** [nodejs/modules#378]
In the spirit of keeping things easily visible, we have at least two parallel out-of-band meeting tracks taking place early September.

1. **Loader Hooks** — #351

   - [x] Last meeting: `Monday Aug 26, 2019 12:00 PM ET` — this was hosted/recorded through my personal zoom account.

   - [ ] Next Meeting: `TBD` (but weekly if I am not mistaken)

<del>

2. **Mitigating the Divergent (specifier) Hazard** — #371 & #368

   - [ ] Next Meeting: `TBD`

</del>

Let's use this thread to coordinate.

**Comment by GeoffreyBooth** [comment]
Wanna make some doodles?

**Comment by SMotaal** [comment]
I'm wrapping of my travels this week… so:

1. For Loader Hooks we're hopefully same time Monday still works for @A-lxe, @bmeck, @guybedford… but hopefully you too @jkrems, and anyone else wanting to join us

   > **Note**: We can arrange a new time when we meet on Monday or doodle if that helps — we ended up going over 1.5 hrs (a 2 hr block being an absolute limit imho).

2. For Divergent Hazard, doodle would be the place to start (probably you @GeoffreyBooth ideally would know the best times to offer there).

**Comment by SMotaal** [comment]
FYI — we're not having the Loader Hooks meeting today.

**Comment by SMotaal** [comment]
I think this thread can be misleading if not kept up-to-date… thoughts?

**Comment by SMotaal** [comment]
Closing:

- No out-of-band meetings intended for Divergent Specifier /cc @GeoffreyBooth

- Loader Hooks folks can open a new thread — also, note that this has been a regular topic in the weekly SES/Frozen-Realms meeting lately.
