### ISSUE TITLE
JSON modules are being reverted on web

### ISSUE THREAD

**Issue by guybedford** [nodejs/modules#391]
See https://github.com/whatwg/html/pull/4943, it appears this is due to lack of consensus between browsers based on a security concern. It does not seem to imply that they won't be implemented in future.

Given that we have erred on the side of web compatibility so far in the implementation, I would like to suggest we bring back the `--experimental-json-modules` flag for Node.js as we unflag modules to indicate the stability of the feature.

For example, were JSON modules to reland but with slightly different semantics (eg `import json from './file.json' as json` has been proposed or similar), then that keeps the door open for Node.js to be able to share in any new semantics.

**Comment by devsnek** [comment]
we don't have the security problem that the web has, I see no reason to destabilise it.

**Comment by ljharb** [comment]
I am also highly skeptical that any new syntax would gain consensus to indicate mime/module type.

**Comment by MylesBorins** [comment]
I think that while stakeholders from the web discuss the feature and figure out if it has a future it is reasonable for us to include the flag, for now. While it is not the most convenient we can use `makeRequire` to synchronously parse JSON objects

**Comment by Fishrock123** [comment]
As far as I am aware, there is no precedent for re-experimental-flagging  a feature. That may be Semver-Major.

**Comment by jkrems** [comment]
Does it change things that the unflagged feature is still behind `--experimental-modules` itself? E.g. it was never "fully" unflagged.

**Comment by MylesBorins** [comment]
I see no problem with re flagging this as the modules implementation itself
is still behind a flag

**Comment by guybedford** [comment]
The PR for Node.js core has been merged here. We can unflag or reconsider stability here at any time further.
