### ISSUE TITLE
New Release Plan

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/modules#400]
As per https://github.com/nodejs/modules/issues/399#issuecomment-540975976 it seems like folks are not comfortable with unflagging modules on LTS without it having lived in a current release for sometime. So here is a suggestion for an alternative path forward.

* Land all changes including aside from unflagging on v13.x ASAP
* Bring https://github.com/nodejs/modules/issues/371 to the TSC meeting next Wednesday specifically with the ask if we should delay the removal of the flag until we have a solution to "dual mode packages"
  * If the TSC is ok with unflagging we land the removal of the flag on 13.x and ship unflagged esm in 13.0.0
  * If the TSC would like us to spend more time on the problem before we unflag we don't unflag on 13.x and spend some time dedicated to that problem space
* Backport all changes to 12.x aside from the flag removal
* Assuming there is not major ecosystem push back we aim to remove the flag in the 1st or 2nd Semver Minor of 12.x LTS (likely in December or March)

Thoughts?

**Comment by jkrems** [comment]
I think that sounds reasonable.

**Comment by targos** [comment]
I think so too

**Comment by GeoffreyBooth** [comment]
Agreed, and I think once we settle exactly what the plan is (get a response from the TSC etc.) I think we should announce the expected release version and date, perhaps in another Medium post. That would invite the public to give `--experimental-modules` one last thorough test before we unflag, to hopefully shake out as many bugs as possible before unflagging.

**Comment by mcollina** [comment]
+1 to the plan. I would personally recommend to drop the flag in v13.

**Comment by kirkouimet** [comment]
@MylesBorins - As of Node 13.0.0 the flag is still required, correct?

**Comment by MylesBorins** [comment]
Yup

**Comment by GeoffreyBooth** [comment]
See https://github.com/nodejs/modules/issues/408#issuecomment-548210350.
