### ISSUE TITLE
`--loader` should parse as ESM

### ISSUE THREAD

**Issue by mikeal** [nodejs/modules#405]
Since the `module` property in package.json allows me to use `.js` and all of my local modules are then only imported using `import` syntax, I’ve gotten in the habit of just using `.js` everywhere even for ESM modules.

This works everywhere but for my `—loader` script, that needs to be `.mjs` because apparently it’s just hitting the default Node.js loader. The thing is, you aren’t actually allowed to use an old style modules for the ESM loader anyway, so this should really just default to assuming the script passed to it is ESM.

**Comment by devsnek** [comment]
I would rather it used normal resolution and failed with "error must be resolvable as esm" than assumed everything was esm.

**Comment by jkrems** [comment]
Does the `package.json#type` field help you there? I agree with @devsnek that if that file sometimes is assumed to be ESM and sometimes isn't, that feels pretty confusing.

**Comment by mikeal** [comment]
> Does the package.json#type field help you there?

Yes, it does seem to. I’ll have to double-check to make sure that it still works once the whole module is in a node_module and referred to by a `bin` but if it doesn’t work then that’s actually a different bug most likely.

Regardless, the current semantics don’t seem right. It should either do what I recommended or give  an error similar to what @devsnek is recommending.

**Comment by guybedford** [comment]
When using the normal `node x.js` entry, we do have some careful error messaging here for the case of trying to load ESM as CommonJS. It could certainly be worth extending that to the `--loader` here if it's not applying already.

**Comment by devsnek** [comment]
we could get rid of quite a lot of ambiguity by getting rid of type:module, but i suspect people will be against that, so i think the reasonable thing to do is apply the full resolution system, load to esm (which means the cjs will show up as { defualt }), and then pick out hooks from the namespace.

**Comment by bmeck** [comment]
closing this as worker around, will note that CJS can have named exports now as well so situation is probably better than last reviewed here.
