### ISSUE TITLE
Info on unflagged modules coming in October v12 LTS seems to be outdated

### ISSUE THREAD

**Issue by borekb** [nodejs/modules#411]
Many blog posts from around the web mention that unflagged modules would come with Node 12 LTS in October 2019, due to [this info in the roadmap](https://github.com/nodejs/modules/blob/35425c9f24d0b6ec1f18305870d7134129ee6a25/doc/plan-for-new-modules-implementation.md#plan-for-new-modules-implementation):

> - Phase 3 improves user experience and extends the MVP.
>
>     - At the completion of Phase 3, the new implementation’s experimental flag will be dropped. The goal is to “release” (drop the --experimental-modules flag) by when Node 12 starts LTS in October 2019.

There seems to a new plan: #400 (Bad Request 😄), maybe the roadmap should be updated?

(I'm opening an issue instead of opening a PR as I just came from one of the blog posts, wondering whether unflagging happened or not; I'm not entirely sure what the current situation is.)

**Comment by GeoffreyBooth** [comment]
As the roadmap said, that was only the _goal._

We’re meeting to discuss this tomorrow: #408. We hope to have a more definitive plan after that.

**Comment by GeoffreyBooth** [comment]
See https://github.com/nodejs/modules/issues/408#issuecomment-548210350. We will unflag as soon as the referenced PRs are ready, hopefully in the next week or two.
