### ISSUE TITLE
Chartering the Modules team

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/modules#412]
Hey all, I'm beyond ecstatic that we were able to reach consensus on unflagging today!

With this consensus behind us I think we should actively explore being chartered by the TSC. Steps to doing so include are documented [here](https://github.com/nodejs/TSC/blob/master/WORKING_GROUPS.md#starting-a-core-working-group)

Requirements include

- [ ] Need at least 3 members
- [ ] Bootstrap Governance

Which we have already done. I do think we should likely do a cleanup of membership before chartering though.

We would then need to open a PR against the TSC repo to add our group to WORKING_GROUPS.md and likely make some small tweaks to README.md and GOVERNANCE.md to s/team/working group

Thoughts?

**Comment by devsnek** [comment]
I was kind of hoping after it was unflagged we could just leave it to normal core processes. People from the group could continue as maintainers of modules in core if they chose to do so.

**Comment by MylesBorins** [comment]
I've seen both Release and Build (for example) get a lot done by being chartered. There is still quite a bit of work that needs to be done including cross ecosystem collaboration with groups like TC39, WhatWG, IETF, etc. Having the regular cadence of meetings and clear ownership over the roadmap will make it possible to engage in those external groups representing node officially. If we only work upstream using defined process we don't really have a good way to officially represent the project, only individuals view points.

Perhaps this is something we decide as a group to not explore though, added the agenda label for discussion.

**Comment by zackschuster** [comment]
is it possible to remain an observer within the charter? i greatly appreciate the notifications.

**Comment by MylesBorins** [comment]
Before chartering the group will likely want to review existing governance
and reach consensus if we wish to continue with the existing structure.

**Comment by jdalton** [comment]
I dig chartering.

**Comment by SMotaal** [comment]
Before chartering, there needs to be a discussion about D&I within the team, there is a lot that imho "hangs" on a "mutual understanding" of including the "often misunderstood boilerplate".

I personally will push for strong D&I text, which I hope others can help write in more clear ways (ie more typical/conventional ways — ie different but not "right" or "wrong" — ie there is more than one way).

**Comment by ljharb** [comment]
What is “D&I”?

**Comment by jkrems** [comment]
"Diversity and Inclusion" I assume. :)

**Comment by MylesBorins** [comment]
We are going to move forward with asking to charter unless there are objections from the team in the next week.

**Comment by MylesBorins** [comment]
Closing as we haven't gotten traction on this

**Comment by ljharb** [comment]
What sort of traction are we missing?

**Comment by MylesBorins** [comment]
We have punted on the discussion in meetings for months. No one has done the work of putting together a charter. TBH at this point I don't think we need to charter.
