### ISSUE TITLE
Countdown to unflagging

### ISSUE THREAD

**Issue by guybedford** [nodejs/modules#426]
The unflagging PR at https://github.com/nodejs/node/pull/29866 is now finally unblocked!

In theory, we already have consensus from the group to unflag this PR, so I wanted to open this issue for any merging-related discussion we might still have here. It has one approval so if it gets another it can land within two days, or otherwise it can land into Node.js master next weekend. I believe we've missed the current patch release, so it would be a little while after that it actually ships. (@MylesBorins / @targos maybe you can share some info on the release cadence to be expected here)

As much docs review as possible would be great. Also if you haven't cloned and built Node.js recently with the current implementation now is the time to clone that branch and play around with it. Who's prepping blog posts!?

**Comment by targos** [comment]
Release plan: https://github.com/nodejs/Release/issues/487

**Comment by guybedford** [comment]
Unflagged has now landed on master.

**Comment by GeoffreyBooth** [comment]
![image](https://user-images.githubusercontent.com/456802/68716296-bfb82a00-0558-11ea-85c1-d87a35b2785a.png)

**Comment by GeoffreyBooth** [comment]
I can work on a blog post. Per @targos’ comment the next release is 2019-11-19 (?) so we need it ready by then?

**Comment by jdalton** [comment]
Awesome!!!
