### ISSUE TITLE
using import for native module

### ISSUE THREAD

**Issue by arlac77** [nodejs/modules#431]
What is the plan for native code imports ?

```js

import { x } from "./something.node";

```

**Comment by jkrems** [comment]
I think they have similar issues to other parts of the require loader: Without running the code, it's not possible to tell what the exports are. So at most we'd support a default export.

Beyond that, IIRC there were multiple people concerned about adding support for native modules with proper WASM bindings just around the corner.

For now, the best way may be to set up a CJS wrapper that can interface with the native code.

**Comment by GeoffreyBooth** [comment]
For now, you can import native code into ESM via `createRequire`:

```js
import { createRequire } from 'module';
import { fileURLToPath } from 'url';

const require = createRequire(fileURLToPath(import.meta.url));

const { x } = require('./something.node');
```

**Comment by bmeck** [comment]
closing as it appears to have no movement and has a workaround, feel free to reopen
