### ISSUE TITLE
Undocumented behavior of package type searches within node_modules

### ISSUE THREAD

**Issue by DerekNonGeneric** [nodejs/modules#436]
As suggested, I've opened an issue for tracking the undocumented behavior of package type searches performed by implementations of the `READ_PACKAGE_SCOPE` algorithm occurring within `node_modules` directories. I've moved my preliminary findings from the code review to this thread to allow for more focused discussions to take place.

**Initial observations (non-exhaustive)**

From the original thread:

*   The upward search seems to stop once it reaches a directory named `node_modules`.
*   Placing a `package.json` with a `"type": "module"` field in a `node_modules` directory doesn't result in `.js` (or even `.mjs`) files as being interpreted to be in ESM context.
*   It's not only loose files adjacent to the `package.json` that aren't switching context. Files within subdirectories of the `node_modules` that contains this `package.json` are similarly unaffected.

This behavior doesn't seem to be documented anywhere, so I'm not sure if is intentional. I'll keep looking and update this issue with any other findings.

Aside from local manual testing, further details can be gleaned from:

1.  The following step<sup>[1](#spec1)</sup> of the `READ_PACKAGE_SCOPE` specification.
    
    > scopeURL ends in a "node\_modules" path segment, return null.
    
2.  The following code block<sup>[2](#spec2)</sup> of the internal implementation.
    
        if (pjson\_url\_path.length() > 25 &&
            pjson\_url\_path.substr(pjson\_url\_path.length() - 25, 25) ==
            "node\_modules/package.json") {
          break;
        }
    

**Conclusion**

If this behavior is by design, the [Package Scope and File Extensions](https://nodejs.org/dist/latest-v13.x/docs/api/esm.html#esm_package_scope_and_file_extensions) section should probably mention it. I'm curious as to what the rationale is behind `node_modules` being a DMZ (de-modularized zone). 😄

* * *

**Footnotes**

<a name="spec1">1</a>: This is step 2.1. in the pseudocode for the `READ_PACKAGE_SCOPE(url)` function located in the [Resolver Algorithm](https://nodejs.org/dist/latest-v13.x/docs/api/esm.html#esm_resolver_algorithm) section of ECMAScript Modules document.  
<a name="spec2">2</a>: This block starts on [line 683 of `module_wrap.cc`](https://github.com/nodejs/node/blob/master/src/module_wrap.cc#L683) in the internal C++ implementation.

_Implications of node\_modules being a DMZ_

*   ESM context cannot cascade into every module of every subdirectory of `node_modules`.
*   Projects currently taking advantage of free bare specifiers in the `/src/node_modules` directory structure pattern may be forced to refactor.
*   // TODO: Add others.

**Comment by Jessidhia** [comment]
My assumption is that it's to avoid breaking packages or symlinks inside the `node_modules/`, which would be resolved by the search algorithm but may not necessarily have a `package.json`.

I don't think it's something that can happen with regular `npm` modules, though; even if you somehow had a package file without a `package.json`, `npm` would need to write its own metadata in there.

**Comment by DerekNonGeneric** [comment]
**Example of implications as promised in https://github.com/nodejs/node/issues/30514#issuecomment-555493361** 

This occurs is in projects with the following directory structure, which resembles mine.

The hierarchy enables access to free bare specifier imports, which is a technique popularized by @Rich-Harris in his [wildly popular tweet](https://twitter.com/Rich_Harris/status/1139908960520220677) about it.

```
// Flags: --es-module-specifier-resolution=node

/lorem/                                  # Hybrid dual-mode package
├──  /bin/
|    └──  lorem                          # CommonJS w/ node shebang
├──  /src/*
|    ├──  /cli/*
|    |    └──  /commands/*
|    |         ├──  help.js*
|    |         └──  run.js*
|    └──  /node_modules/                 # Free bare specifiers for local modules
|         └──  package.json              # This should be the only thing required!
|         └──  /common/*
|         |   ├──  /index.js*
|         |   ├──  /utils.js*
|         |   └──  /constants.js*
|         └──  /ipsum/*
|         └──  /dolor/*
|         └──  /set/*
|         └──  /amet/*
|         └──  loosemodule.js*            # import('loosemodule')
├──  /node_modules/                       # 3P deps from npm
└──  /package.json                        # Cannot be a hybrid package w/ type: "module"

* earmarked for ESM
```

To enable ESM in projects with this current structure post-unflagging, it should be as simple as adding `"type": "module"` to the root `package.json`, right? Well, to maintain the current resolution algorithm, the `--es-module-specifier-resolution=node` will need to be enabled, which isn't too bad. However, as it currently stands, every single one of those directories with asterisks will need a package manifest specifying module type in them too. Why?

I'm not sure if it's too late to reconsider current behavior, but I imagine it snuck up on everyone who didn't read the C++ code or algorithm spec. Please at least highlight it in the documentation!

**Comment by MylesBorins** [comment]
@DerekNonGeneric could `--experimental-resolve-self` combined with export maps allow for similar behavior without the resolution algorithm?

**Comment by DerekNonGeneric** [comment]
/to @MylesBorins

> could --experimental-resolve-self combined with export maps allow for similar behavior without the resolution algorithm

If I understand correctly, that would also require a `package.json` in each of the subdirectories because `package.json` is not recognized when it is inside of `node_modules`. When importing that module in the `index.mjs`, it wouldn't be recognized as an ES module. So I tried putting a type: module manifest inside of the subdir and I got a very weird error. It seems like the ESM loader is trying to load the manifest as a module. What follows is my attempt. It's possible that I did something wrong, please let me know.

`lorem/package.json`:
```
  "name": "lorem",
  "exports": {
    ".": [
      "./index.mjs"
    ]
  }
```

`lorem/index.mjs`:
```
import * as constants from './src/node_modules/shared/constants.js';
export default constants;
```

`lorem/x.mjs`:
```
import lorem from 'lorem';
```

Run the following command.
```
node --experimental-resolve-self x.mjs
```

Error:
```
(node:16589) ExperimentalWarning: The ESM module loader is experimental.
internal/modules/run_main.js:50
    internalBinding('errors').triggerUncaughtException(
                              ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension: /mnt/c/apps/lorem/package.json
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:114:13)
    at Loader.resolve (internal/modules/esm/loader.js:74:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:148:40)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:41:40)
    at link (internal/modules/esm/module_job.js:40:36) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

**Comment by ljharb** [comment]
What do you mean by, package.json is not recognized in node_modules?

**Comment by DerekNonGeneric** [comment]
@ljharb, the ESM resolver bails before it can read `type: module` from the `package.json` located in the `node_modules` root (`/node_modules/package.json`).

**Comment by ljharb** [comment]
@DerekNonGeneric that's not how type module is supposed to work; only the closest package.json can set it. so `./node_modules/package.json` won't affect *anything* unless there's a dir inside `node_modules` that has no `package.json` (which is super rare)

**Comment by DerekNonGeneric** [comment]
> [...] unless there's a dir inside node_modules that has no package.json (which is super rare)

Albeit rare, this is precisely the use-case that currently lacks support. I was able to solve this issue by implementing a modified version of `ESM_FORMAT` (from the spec) in userland JS from within a loader. It's working very well. I have yet to compare its performance to the internal implementation via proper benchmarking, but that will be next.

**Comment by DerekNonGeneric** [comment]
After chatting with a few others from the modules team, I was informed that the "node" resolution mode will likely be removed rather than becoming the default. In light of this information and the solution proposed above, a PR to Node core for additional support of this directory structure will likely not be necessary. I don't foresee myself continuing to use this project directory structure, which is a "hack" after all. If I uncovered a bug in my above attempt at the suggestion, I will try to create a reduction and file a separate issue about it. As such, the only actionable item remaining in this issue would be considering illuminating `node_modules` as a package boundary in the documentation. If it is determined that the algorithm pseudocode is sufficient, please feel free to close this issue.

**Comment by GeoffreyBooth** [comment]
If I remember correctly, the special handling of `node_modules` was to avoid breaking files or symlinks placed in `node_modules/.bin`, since that folder doesn’t contain a `package.json` and assumes CommonJS mode. We wouldn’t want it to break if the user adds `"type": "module"` to their app’s `package.json`, which would otherwise trickle down into `node_modules/.bin`. Then again, it would be a pretty trivial fix for `npm` to just start putting a `package.json` containing `{"type": "commonjs"}` into that folder, assuming `.bin` is an `npm`/`npx`-only thing.

As far as replicating the behavior of that popular tweet, `"exports"` and `resolve-self` should provide a less hacky equivalent:

```js
// package.json
"name": "foo",
"type": "module",
"exports": {
  ".": "package-main-entry-point.js",
  "./utils/": "./src/utils/"
```

```js
// package-main-entry-point.js
import { shuffle } from 'foo/utils/shuffle.js';
```

I haven’t tested the above code, but if I understand correctly this is how `--experimental-resolve-self` is supposed to work. cc @jkrems

**Comment by DerekNonGeneric** [comment]
/to @GeoffreyBooth

Thanks. Unfortunately, the self-reference solution would require refactoring the codebase. At the very least, all of the specifiers would need to be updated. Adding the specifier-path mappings would also be another chore (probably needs to be autogenerated by a separate tool).

**Comment by GeoffreyBooth** [comment]
> Unfortunately, the self-reference solution would require refactoring the codebase.

Then just add `package.json` files into each subfolder of your custom `node_modules`.

**Comment by DerekNonGeneric** [comment]
To get this issue closed, I believe the consensus was to put the algorithms more front-and-center.

I think to accomplish this, at the very least, we should keep these algorithms' details expanded. On the left you can see how it looks by default, on the right is how it looks expanded (after tapping it). 

https://nodejs.org/api/esm.html#esm_resolver_algorithm

![proposal](https://user-images.githubusercontent.com/17770407/77213044-c7c43f80-6adf-11ea-9e71-fd397d0811fc.png)

There is prior art on this with the [All Together...](https://nodejs.org/api/modules.html#modules_all_together) section of the Modules API docs.

![all-together](https://user-images.githubusercontent.com/17770407/77213324-d5c69000-6ae0-11ea-853f-492b4a8ec7e2.png)

**Comment by DerekNonGeneric** [comment]
/to @GeoffreyBooth

This relates to UX and user journey. Is there anyone else who you think has an opinion on this before I seek input via a PR?

**Comment by GeoffreyBooth** [comment]
I'm not sure why the algorithm needs to be expanded. It feels like information for a very select audience, namely developers implementing tools that work closely with Node's resolution. The general audience shouldn't need to know the detailed algorithm.
