### ISSUE TITLE
Backporting regression fix from master to 9.x

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/modules#44]
Hey All,

we have an open PR to backport a change to modules from master to 9.x

https://github.com/nodejs/node/pull/18923

Are there objections to landing this? As it had been landed on master prior to us deciding that we wanted to discuss a code freeze, I think it makes sense to backport.

**Comment by jdalton** [comment]
I don't see this as controversial but bugs in something experimental is nothing new so I don't see this as a major need.

**Comment by benjamingr** [comment]
> Are there objections to landing this? As it had been landed on master prior to us deciding that we wanted to discuss a code freeze, I think it makes sense to backport.

In general, I think that:

 - The consensus is against a code freeze at the moment, while we agreed that the current implementation might break in incompatible ways.
 - We should default to the current status, as we're not a chartered working group - even if we wanted to object to landing something we should likely do so in the "regular" way (in the PR)

**Comment by MylesBorins** [comment]
Thanks for chiming in folks. I landed the backport. We can discuss further in the meeting next week
