### ISSUE TITLE
Stabilizing the resolver

### ISSUE THREAD

**Issue by guybedford** [nodejs/modules#451]
I'd like to suggest that we mark a new phase target for **resolver stability**.

In particular the features here are package self-resolution and dual mode support (currently via conditional exports), which we agreed to support by end of Jan in some form.

As per https://github.com/nodejs/modules/issues/450, for 12.x stability I think it is important that our changes to the CommonJS resolver can be included in 12.x as soon as possible, since the next release deadline would be for Jan.

The concern is that users shipping "exports" for 13.x users may find the code uses "main" fine in 12.x, but then when we backport modules to 12.x in April the "exports" resolution kicks in on that branch and there may be breakage. To avoid this scenario we would ideally be able to ship "exports" from Jan already now on 12.x so that users shipping "exports" code for 13.x immediately can see the 12.x compatibility of their code, making it a compatibility issue of the act of shipping itself. The sweet spot we are in is that no one has shipped "exports" yet, so we can still define what breakage means. But once enough time passes we no longer have that luxury.

**Comment by ljharb** [comment]
As one data point, I'm planning to release deep-equal v2 and tape v5 within the next few weeks, which will have transitive deps using "exports"; the window for that luxury seems quite short.

**Comment by guybedford** [comment]
Having those packages use the "exports" entry point on an upgrade path for v12 likely won't be breaking though right? The issue is when enough users ship "exports" that the 5% probability of a break is big enough to be an issue.

**Comment by ljharb** [comment]
So, since I was able to use the array RHS form for `.`, it works on v13.0/v13.1, as well as v13.2. If either's functionality arrives in 12.x, then while it's technically breaking since previously requireable files will stop being so, in practice I doubt it will be an issue.

However, if the *exact semantics* of either 13.0-1, or 13.2+, aren't what 12.x gets, then the breakage may be significant.

**Comment by guybedford** [comment]
With `--experimental-conditional-exports` unflagged there are no other current experimental proposals for the proposal, apart from possibly the package imports field - https://github.com/jkrems/proposal-pkg-exports#3-imports-field.

We can leave this issue open to discuss any further proposals or that proposal, or close it. I do think it is important we try to move to a point of considering the resolver as stable as possible... ideally this is not an area that should change too much.

**Comment by ljharb** [comment]
The only remaining item i can think of is a self export sigil.

**Comment by DerekNonGeneric** [comment]
I was really bummed out that there wasn't enough time to get to this in the previous meeting. I was hoping for some development regarding what @guybedford spoke about in https://github.com/nodejs/node/issues/30514#issuecomment-558886269.

> [..] work with core to get the unit tests made as a suite that can be tested against userland resolvers

Am I correct in thinking that this is the issue tracking that effort?

**Comment by guybedford** [comment]
@DerekNonGeneric thanks for bringing that up. Having portable tests for the resolver is definitely an important part of its stability that has so far been overlooked in this thread (although was discussed in the meeting as you point out).

I've created a new tracking issue for this at https://github.com/nodejs/node/issues/49448.

In terms of new resolver features, personally I'm not likely to push "imports" anytime soon as I feel "exports" gets a good coverage of the usefulness there. But if anyone would like to create issues for this or any other new resolver features please do go ahead.

So I'll close this issue then for now as moving on these sub-issues rather.
