### ISSUE TITLE
Update node.js github bot to auto label modules issues

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/modules#460]
Need to add a regular expression to [this file](https://github.com/nodejs/github-bot/blob/master/lib/node-labels.js#L5) so the bot knows which files it should match to auto apply the label [`ES Modules`](https://github.com/nodejs/node/pulls?q=is%3Aopen+is%3Apr+label%3A%22ES+Modules%22)

This is a good first issue!

**Comment by phillipj** [comment]
This issue can be closed as it was solved in https://github.com/nodejs/github-bot/pull/249 and is live and kicking in production.
