### ISSUE TITLE
Why aren’t built‑in ESM exports synced automatically?

### ISSUE THREAD

**Issue by ExE-Boss** [nodejs/modules#481]
Currently, it’s&nbsp;necessary to&nbsp;manually call&nbsp;[`Module.syncBuiltinESMExports()`](https://nodejs.org/docs/latest-v12.x/api/modules.html#modules_module_syncbuiltinesmexports) after&nbsp;making&nbsp;changes to&nbsp;built‑in&nbsp;exports.

This&nbsp;makes&nbsp;me wonder&nbsp;why wasn’t&nbsp;this&nbsp;implemented using&nbsp;a&nbsp;`Proxy`‑based sync‑on‑write&nbsp;mechanism.

A&nbsp;`Proxy`‑based sync‑on‑write&nbsp;solution could&nbsp;also only&nbsp;update the&nbsp;exports that&nbsp;changed, instead&nbsp;of&nbsp;looping over&nbsp;all built‑in&nbsp;modules and&nbsp;their&nbsp;exports.

**Comment by bmeck** [comment]
This was the case originally, but problem with accessors (particularly getters) caused issues. See:

* https://github.com/nodejs/node/pull/29426
* https://github.com/nodejs/modules/blob/master/doc/meetings/2019-09-25.md#nodejsnode
* https://github.com/nodejs/node/pull/29737

**Comment by MylesBorins** [comment]
I'm going to go ahead and close this as it seems like the original question was answered
