### ISSUE TITLE
Revisiting removing experimental warning

### ISSUE THREAD

**Issue by guybedford** [nodejs/modules#499]
The PR to remove the experimental modules warning is still sitting at https://github.com/nodejs/node/pull/31974, with the explicit steps to unblock not completely clear.

It would be good to revisit this discussion now that we are coming on 14 being released next week.

Many tools that want to adopt ES modules in Node.js would benefit a lot from this warning being removed.

**Comment by MylesBorins** [comment]
So I think we might be able to squeeze this into 14.0.0 if we have high level agreement between parties, but we would want to get the PR landed ASAP. Anyone have concerns with doing this?

**Comment by MylesBorins** [comment]
Unless someone objects I plan to land https://github.com/nodejs/node/pull/31974 in 12 hour

**Comment by MylesBorins** [comment]
We landed it :P
