### ISSUE TITLE
Why require .cjs extension with `require` field.

### ISSUE THREAD

**Issue by thysultan** [nodejs/modules#500]
In the following example why does `require` need to point to a `.cjs` extension? it seems counter-intuitive to it's purpose.

```js
// ./node_modules/pkg/package.json
{
  "type": "module",
  "main": "./index.cjs",
  "exports": {
    "import": "./index.mjs",
    "require": "./index.cjs"
  }
}
```

For example this is what i wanted to do:

```js
// ./node_modules/pkg/package.json
{
  "type": "module",
  "main": "./index.umd.js",
  "exports": {
    "import": "./index.esm.js",
    "require": "./index.umd.js"
  }
}
```

**Comment by jkrems** [comment]
The `exports` fields uses conditions, it doesn't describe file formats. It's completely valid (even though not frequently useful) to write something like this:

```js
{
  "name": "foo",
  "exports": {
    "require": "./x.cjs", // this is CommonJS
    "import": "./y.cjs" // this is CommonJS as well!
  }
}
```

From a CommonJS file, both can be loaded:

```js
require('foo'); // we use require, so the require condition applies
import('foo'); // we use import, so the import condition applies
```

The condition doesn't "care" that the consuming file is CommonJS or that the targeted file is CommonJS. It only matters which module loader is used when requesting the package: require or import.

Node tries very hard to ensure that the same file can only be loaded in one format, unambiguously. If we would use the condition to tell that `index.umd.js` should be treated as CommonJS, it would be possible to write the following:

```
{
  "type": "module",
  "exports": {
    "import": "./index.js",
    "require": "./index.js" // Oops, index.js is both ESM and CJS..?
  }
}
```

So, to finally answer your actual question, `"type": "module"` is why `.cjs` is required. The following are equivalent:

#### Treat yolo-script (.js) as ESM

```js
// ./node_modules/pkg/package.json
{
  "type": "module",
  "exports": {
    "import": "./index.js",
    "require": "./index.cjs"
  }
}
```

#### Treat yolo-script (.js) as CJS

```js
// ./node_modules/pkg/package.json
{
  "exports": {
    "import": "./index.mjs",
    "require": "./index.js"
  }
}
```

#### Explicit file types for both CJS and MJS

```js
// ./node_modules/pkg/package.json
{
  // type field has no effect
  "exports": {
    "import": "./index.mjs",
    "require": "./index.cjs"
  }
}
```

For the docs, we went with that last option because it's the clearest. It's immediately visible which files are CJS and which are ESM without having to find the `package.json` file and look at the `type` field.

**Comment by thysultan** [comment]
>we use require, so the require condition applies

Yes this is what i expected. calling `require('pkg')` should load the `pkg.exports.require` file regardless of it's extension. Is this not the case?

**Comment by MylesBorins** [comment]
This is the case.

One more thing that is important to point out is that package.exports does
not apply the node.js file extension resolution algorithm. You need to
include the full path the the file you wish to load.

**Comment by thysultan** [comment]
>This is the case.

So it will load it as a commonjs module per `require()` functions semantics?

**Comment by jkrems** [comment]
> So it will load it as a commonjs module per require() functions semantics?

Inside of `type:module`, a `.js` file is never CommonJS. So the require semantics are that it throws because it doesn't support `.js` files in `type:module`. The same would happen outside of exports:

```js
// a.cjs
console.log(require('./b.js')); // throws! .js isn't supported by require inside of type:module

// b.js
module.exports = 42;
```

**Comment by thysultan** [comment]
Yes, however i'm not trying to load a file from `require()` but a package so i expect `require('pkg')` to load the `pkg.exports.require` file as `commonjs`.

**Comment by bmeck** [comment]
@thysultan `require()` does not exclusively load `commonjs`, it can load JSON / C++ / other files. I don't understand the expectation/question. It is perfectly valid to have `pkg.exports.require` point to a C++ module for example. The require() does not determine the format of the file, the package does by the filesystem and `pkg.type` .

**Comment by thysultan** [comment]
Is it possible to add the following to make this possible?

```js
{
  "type": "module",
  "main": "./index.umd.js",
  "exports": {
    "require": {type: 'cjs', main: '"./index.umd.js"'}
  }
}
```

**Comment by GeoffreyBooth** [comment]
> Is it possible to add the following to make this possible?

What you're asking for is another way to tell Node to treat a particular file as CommonJS. Currently there are two ways to tell Node to treat files as CommonJS: use the `.cjs` extension, or use the `.js` extension in a `type: module` package scope. That's it. Adding more methods increases complexity for little benefit.

If you want to use `.js` as your extension for both CommonJS and ESM files, you need to use subfolders:

```
- ./package.json               - has "type": "module"
- ./dist-module/index.esm.js   - loaded as ESM via package.json in parent folder
- ./dist-commonjs/package.json - has "type": "commonjs"
- ./dist-commonjs/index.umd.js - loaded as CommonJS via package.json in same folder

**Comment by thysultan** [comment]
>What you're asking for is another way to tell Node to treat a particular file as CommonJS

I'm only asking this because the current implementation of `exports: {require: ...}` doesn't include a way to encode this into `pkg.exports` without resorting to the extension `.cjs`

**Comment by ljharb** [comment]
@thysultan it does if you’re not using type:module - doing that is why you’ve constrained yourself to .cjs for CJS.
