### ISSUE TITLE
CLI flag `--experimental-modules`

### ISSUE THREAD

**Issue by coreyfarrell** [nodejs/modules#502]
I just ran `node --help` on v14.0.0-rc.3, I was surprised to see that `--experimental-modules` was still listed.  I understand why this flag is still tolerated by the CLI but should it be be hidden from the help listing as it no longer needs to be specified?

**Comment by MylesBorins** [comment]
@coreyfarrell I opened a PR to fix this

**Comment by aduh95** [comment]
I think the fix has landed in 14.1.0, should this stay open?
