### ISSUE TITLE
Adding a `--loader` makes extensionless files fail to run

### ISSUE THREAD

**Issue by giltayar** [nodejs/modules#512]
To reproduce:

1. Generate a runnable extensionless file (let's call it `runcjs`):

```js
#!/usr/bin/env node

console.log('hello')
```

(note that the hashbang has nothing to do with it and can be removed. I just found it out because I was trying to run a file in `./node_modules/.bin` and those are usually extensionless)

2. Run it with node:

```sh
node ./runcjs
```

This works!

3. Now add a loader (empty mjs file):

```sh
node --loader=./empty.mjs ./runcjs
```

This fails with the exception `[ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for ../runcjs`

This was tested with Node v14.2.0.

**Comment by ljharb** [comment]
I believe this is also https://github.com/nodejs/node/issues/33226 ?

**Comment by giltayar** [comment]
Yup, sorry. Duplicate. I'll close this. Thanks!

**Comment by DerekNonGeneric** [comment]
You may be able to this for now.

```console
node --experimental-specifier-resolution=node --experimental-loader=./empty.mjs ./runcjs
```

You'll need to do something with that `getFormat` loader hook though.

```javascript
// empty.mjs
export async function getFormat(url, context, defaultGetFormat) {
  return {
    format: 'commonjs',
  }
}
```

This workaround may also be a clue to what's currently bugged too.
