### ISSUE TITLE
Using multiple loaders

### ISSUE THREAD

**Issue by aurium** [nodejs/modules#513]
Imagine having transpiler loaders for N languages, network access loaders, encrypted source loaders... To some tasks we may need more than one loader in a Node.js project.

I think "`--experimental-loader`" don't support an array of loaders, so what is the best path? Implement the support on Node.js or make a loader of loaders? _(I believe it must be a Node.js feature)_

Regardless of the chosen path, simply create a line of hooks (where the "defaultHook" parameter is the next loader hook) is enough? I think yes. Is there something to consider?

**Comment by GeoffreyBooth** [comment]
There’s a `nodejs/loaders` repo now to organize ES module loaders work. “Multiple loaders“ or chaining loaders, as we’ve been calling it, is on the roadmap: https://github.com/nodejs/loaders#upcoming.
