### ISSUE TITLE
Import CJS named exports via DefinitelyTyped TypeScript declaration files

### ISSUE THREAD

**Issue by dfabulich** [nodejs/modules#521]
(I know this sounds crazy, but hear me out.)

Today, ESM scripts can't import CJS named exports, because ESM named exports must be determined at parse time, but CJS named exports can't be computed until execution time.

To fix this, https://github.com/nodejs/node/pull/33416 attempts to automagically detect CJS exports by parsing their source. It works almost 62% of the time, which is both impressively high and depressingly low. (At a minimum, it fails in all cases where the library uses CJS default exports.)

That got me thinking, "If only there were some declarative file format that could define the names that CJS libraries export! We could even crowdsource the export names."

But there _is_ such a file format: TypeScript declaration files.

If we want to know what names `request` exports, it's possible in principle to try looking it up in `node_modules/@types/request/index.d.ts`.

Too brittle? Don't want to take a TypeScript dependency in core? We could maintain a repository that mirrors https://github.com/DefinitelyTyped/DefinitelyTyped, using the current latest version of TypeScript's parser to transform all of the `.d.ts` files into simple JSON files, including nothing but an array of export names.

If parsing CJS scripts to detect named exports is on the table, then maybe we should consider this, too.

**Comment by zackschuster** [comment]
from my experience, out-of-band information is a hard sell; it took a very long time to reach consensus on even looking at package.json for module data. 

you'll also need to address the overhead from checking for all these files; `stat` calls aren't free. i don't think this is doable, personally — it's one of the biggest pain points in module resolution & the main reason (afaict) we don't have extensionless imports today.

however! if you got a convincing enough PR together, i think a lot of people here would be willing to give you honest feedback. :)

**Comment by ljharb** [comment]
The majority of modules that people would want to named-import from are CJS modules that will *never* be updated. A solution that doesn't work for pure JS that hasn't been touched since 2012 just won't really work (since the existing more-than-sufficient solution for "code that gets updated" is "write a simple wrapper .mjs file").

**Comment by bmeck** [comment]
We have taken the lexical parsing approach to solve this issue
