### ISSUE TITLE
reach out to WASM implementors

### ISSUE THREAD

**Issue by bmeck** [nodejs/modules#54]
Per the [State of WebAssembly videocast today](https://youtu.be/D3Kf7HZyOrQ?t=1h58m25s). It seems they are trying to find out who are in charge of integrating with the Node.js module ecosystem, it was mentioned several times but I linked the easiest one to get some minor context.

We could setup a meeting maybe, and it sounded like @flagxor might be a good contact point to open the communication channel with.

@linclark , you might be the person best suited to get some high level information or background on this since you have been doing some WASM work as well.

**Comment by bmeck** [comment]
The link should take you to the point that makes the most sense. Mostly, they just are unsure about how WASM will integrate with Node and have no idea what will be done to load WASM right now.

**Comment by linclark** [comment]
I'm attending both the WebAssembly CG calls and the Node modules WG calls, so I'd be happy to serve as a bridge between the two. 

Luke Wagner and I will also be at the Node Collaborators Summit (https://github.com/nodejs/summit/issues/62) this summer to talk about WebAssembly things.

**Comment by bmeck** [comment]
this happened
