### ISSUE TITLE
Use Cases (Tracking Issue)

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/modules#55]
Let's use this issue to track our Use Cases discussion. We will be iterated on the use cases in a [google doc](https://docs.google.com/document/d/10BBsIqdAXB9JR2KUzQGYbCiVugYBnxE4REBakX29yyo/edit) and discussing meta points in this thread.

This will be an ongoing agenda item until we have consensus on core use cases.

Google Doc: https://docs.google.com/document/d/10BBsIqdAXB9JR2KUzQGYbCiVugYBnxE4REBakX29yyo/edit

This trumps https://github.com/nodejs/modules/issues/41 which was originally about making a standalone meeting

**Comment by jdalton** [comment]
In the 2018-04-11 meeting we started extracting features from the [use cases](https://docs.google.com/document/d/10BBsIqdAXB9JR2KUzQGYbCiVugYBnxE4REBakX29yyo/edit) and have began to list them [in this document](https://docs.google.com/document/d/1HuH5E1d_mNuziBxPDRZVjpdfmUPhqVg0MUUcYDnqwn8/edit). We could ask that features are added during the next meeting (so hold off adding new ones until then) but please feel free to continue to add to the [use cases](https://docs.google.com/document/d/10BBsIqdAXB9JR2KUzQGYbCiVugYBnxE4REBakX29yyo/edit) in the meantime. When adding use cases please start at the bottom of the document and increment the number. Re-arranging use cases will cause confusion and misalignment.
