### ISSUE TITLE
Document node: scheme

### ISSUE THREAD

**Issue by Jamesernator** [nodejs/modules#555]
Since at least Node 14 one can import builtin modules using the `nodejs:` scheme. e.g. `import fs from "nodejs:fs";` or `import("nodejs:fs")`. However this capability doesn't seem to be documented anywhere (particularly not on the [esm docs](https://nodejs.org/dist/latest-v14.x/docs/api/esm.html)).

It would be good to either document this, if it is officially supported, or to warn when `nodejs:` scheme is used (if it's only for internal use).

**Comment by bmeck** [comment]
@Jamesernator that isn't stable and actually has been a discussion on if it should be `node:` since that is what policies use. Whenever we converge it will be documented

**Comment by bmeck** [comment]
https://github.com/nodejs/node/pull/35387 has landed so the features have unified on `node:`, do we want to officially document this now? We have a semi-implicit documentation bit in the resolver spec already.

**Comment by bmeck** [comment]
made a PR to docs

**Comment by bmeck** [comment]
this has landed
