### ISSUE TITLE
Proposal: ESM should not export PromiseLike instance

### ISSUE THREAD

**Issue by loynoir** [nodejs/modules#571]
### Proposal
ESM should not export PromiseLike instance

### Reason
-  If all ESM export are not PromiseLike instance (which seems not possible yet), and detects no top-level-await within all module foo stuff (which is not easy but seems possible), then 

`(await import(foo)).bar`

can be safely written to below, I guess, 

`__toModule(require_foo()).bar`

no need top-level-await in target environment

- no `awaitOnce`.
- And from my limited experience, I don't know any library export  PromiseLike instance

### Scenario
Here's a fallback

```js
/**
 * @type {typeof ReadableStream}
 */
let RS
if (typeof ReadableStream !== 'undefined') {
  RS = ReadableStream
} else {
  try {
    RS = (await import('node:stream/web')).ReadableStream
  } catch {
    RS = (await import('web-streams-polyfill')).ReadableStream
  }
}

export default RS
```

Here's bundler output, need TLA in target environment
```sh
$ esbuild --bundle --format=esm ...
```

```js
var RS;
if (typeof ReadableStream !== "undefined") {
  RS = ReadableStream;
} else {
  try {
    RS = (await import("node:stream/web")).ReadableStream;
  } catch {
    RS = (await Promise.resolve().then(() => __toModule(require_polyfill_min()))).ReadableStream;
  }
}
```

**Comment by loynoir** [comment]
Emm, any thoughts on how to state an ESM module `(await import(foo)).foo` can let bundler transform to `__toModule(require_foo()).bar`, for target environment without top-level-await?

As there is a bundler here, no need to resolve things.

**Comment by ljharb** [comment]
If you’re asking about how to transpile TLA, that can’t be done without cross-file knowledge (which a bundler does have, to be fair) and artificially forcing the rest of the module graph to be dependent on the TLA’d Promise. I doubt it’s a simple transform, but i believe it’s possible.

**Comment by loynoir** [comment]
Is there a form of writing fallback import, without using TLA?

**Comment by ljharb** [comment]
Importing ESM is always asynchronous, so no, I don't believe there is - short of using CJS instead.
