### ISSUE TITLE
`import.meta.url` is `undefined` inside module file.

### ISSUE THREAD

**Issue by trusktr** [nodejs/modules#576]
I'm running a file like this:

```bash
node --input-type module --experimental-import-meta-resolve < ./dev-server.js
```

And inside that file we have this:

```js
console.log(import.meta.url)
console.log(import.meta.resolve)
process.exit()
```

and this is the output:

```
undefined
undefined
```

**Comment by trusktr** [comment]
Oh, that makes sense, because it is piped into the command, Node has no idea what the URL is.

If I rename it to `.mjs` and run it like so it works:

```js
node --experimental-import-meta-resolve ./dev-server.mjs
```

I must be missing something simple. How do we run a regular `.js` file as esm?

**Comment by GeoffreyBooth** [comment]
> I must be missing something simple. How do we run a regular `.js` file as esm?

Add `"type": "module"` to the nearest parent `package.json`. If you have further questions please use https://github.com/nodejs/help, this repo is for the team developing the modules implementation.

**Comment by trusktr** [comment]
It'd be great if `node --input-type module ./dev-server.js` should just worked.
