### ISSUE TITLE
Topics to discuss with TC39

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/modules#84]
Meeting is next week. I think we missed the boat to get something on the agenda but I can ask the chairs.

What are specific questions that we can ask the group or socialize during hallway track

**Comment by ljharb** [comment]
Things can still be added to the agenda if they're not seeking advancement; but the agenda is already over-full, so I don't anticipate there being any time to get to any additions.

**Comment by guybedford** [comment]
Ref spec issue - https://github.com/tc39/ecma262/issues/1195.

**Comment by MylesBorins** [comment]
Will open a new issue for future meetings
