### ISSUE TITLE
Next meeting on 2018-05-30?

### ISSUE THREAD

**Issue by GeoffreyBooth** [nodejs/modules#92]
In https://github.com/nodejs/modules/issues/90#issuecomment-390366140 it was suggested that we reschedule the May 23 meeting because many people will be unavailable due to a TC39 meeting. Can we push the meeting one week to May 30? At the same time.

I’m assuming we would then continue every two weeks thereafter (June 13, June 27, etc.) but we can figure that out at the meeting.

**Comment by devsnek** [comment]
we might want to push it back 10-15 min so we don't bump the @nodejs/diagnostics meeting

**Comment by benjamingr** [comment]
May 30th is a day before the node summit and a lot of people will be traveling.

We do have a meeting during the summit though.

**Comment by GeoffreyBooth** [comment]
> We do have a meeting during the summit though.

A modules meeting during the summit? When?

**Comment by benjamingr** [comment]
During the first day (May 31st):

> 11:00 - 12:30	Workshop (meeting room): Modules	@MylesBorins

[See the nodejs/summit post here](https://github.com/nodejs/summit/issues/60#issue-300668550).

In case it is not clear, you are invited to participate in the summit and in that session in particular. You are also welcome to file for travel expenses (see https://github.com/nodejs/modules/issues/48 ) - I don't think you participated when that was posted.

**Comment by GeoffreyBooth** [comment]
I didn't think that applied to me. Will there be a Zoom or similar I could login to?

**Comment by benjamingr** [comment]
@GeoffreyBooth that meeting will be face-to-face, you are welcome to attend.

Do we have plans to allow remote participation in the meeting or does that complicate it @MylesBorins ?

**Comment by mhdawson** [comment]
I can't make this week and will be travelling next week to the summit so only 50% that I'd make next week.

**Comment by MylesBorins** [comment]
I think we should keep the initial meeting for this wednesday. I am most likely not able to attend, but perhaps @jdalton can chair again.

If we don't have quorum there are still a bunch of things that can be talked about.

If we want to make a permanent change to the meeting schedule we should likely run another doodle

**Comment by ljharb** [comment]
Specifically I do not think we should have a decision on transparent interop, whether we have quorum or not.

**Comment by benjamingr** [comment]
@ljharb 

> Specifically I do not think we should have a decision on transparent interop, whether we have quorum or not.

I don't think we've reached that point yet anyway.

**Comment by jdalton** [comment]
@MylesBorins 
> I think we should keep the initial meeting for this wednesday. I am most likely not able to attend, but perhaps @jdalton can chair again.

I can. We'll need a foundation member to attend too.

@ljharb 
> Specifically I do not think we should have a decision on transparent interop, whether we have quorum or not.

Ya, we can hold off on that. This week won't be a good week for that.

**Comment by GeoffreyBooth** [comment]
Okay, I’m happy to close this and keep the next meeting at 2018-05-23 unless there’s anyone else who’d prefer otherwise.

@MylesBorins will it be possible to have the summit meeting on webchat somehow?

**Comment by benjamingr** [comment]
@jdalton

> I can. We'll need a foundation member to attend too.

I don't know if that's the answer you were looking for but as a modules team member you are entitled to join the foundation - there is a post explaining how to do so at https://github.com/nodejs/members and https://github.com/orgs/nodejs/teams/members/discussions/6 (both these links are only applicable to members).

Or did you mean something else?

**Comment by jdalton** [comment]
@benjamingr 

> I don't know if that's the answer you were looking for but as a modules team member you are entitled to join the foundation 

Ah, I've joined that :tada: 

> Or did you mean something else?

I meant someone with admin zoom access and all the youtube rights to stream/record.

**Comment by MylesBorins** [comment]
I can at the very least join when the meeting starts kick off the stream and make someone else the host

Will open agenda issue v soon
