### ISSUE TITLE
Feature: Runtime loaders, transpilation at import time

### ISSUE THREAD

**Issue by GeoffreyBooth** [nodejs/modules#96]
Just as we can do:

```coffee
# app.coffee
require 'coffeescript/register'
{ slice } = require './pizza.coffee'
```
or
```js
// app.js
require('babel/register');
const { slice } = require('./pizza.js');
```
we should be able to achieve the equivalent in ESM, e.g. `import` a CoffeeScript file or `import` a JavaScript file that requires transpilation. References: [CoffeeScript register](http://coffeescript.org/#nodejs-usage), [`babel-register`](https://babeljs.io/docs/usage/babel-register/).

Use case 4. Related to #82.

**Comment by ljharb** [comment]
I’m not sure the first example works - you have to require the register module before you’re able to require or run coffeescript.

**Comment by GeoffreyBooth** [comment]
@ljharb I didn’t flesh it out, but the first example works if run via `coffee`, as in `coffee app.coffee`. But it turns out that using that method means you don’t need `register`, so I guess you’re right in that sense. If the file were transpiled into `app.js` and then run via `node app.js`, you would need the `register`:

```js
// app.js, transpiled from app.coffee above
var slice;

require('coffeescript/register');

({slice} = require('./pizza.coffee'));
```

**Comment by bmeck** [comment]
@GeoffreyBooth to clarify, does this request require you to mutate the loader pipeline at runtime? If the loader needs to be declared somewhere outside of evaluation that does seem to fit this use case on a glance, but differs in workflow from your example (easier to analyze though).

**Comment by Janpot** [comment]
Also, if such loaders (as declared via the CLI flag or package.json) existed, wouldn't that mean you could write a loader that allows mutating the loader pipeline at runtime?
